// @uniwork/views HTML visual document ops. Pure builders that turn an intent
// (replace, insert, move, style) into an UpstreamPatchSet applied through the
// engine's validated patch path - never a string splice. No React, no DOM, no
// host port, so the web host and the desktop renderer share one implementation.
export {
  ancestorsOf,
  attributeInsertionPoint,
  decodeAttributeValue,
  elementByPath,
  elementBySid,
  elementCovering,
  encodeAttributeValue,
  findAttribute,
  HtmlOpError,
  insertAt,
  isDescendant,
  parseStartTagAttributes,
  patchSet,
  replaceRange,
  requireElement,
  resolveElement,
  type HtmlAttribute,
  type HtmlElementEntry,
  type HtmlOpErrorCode,
  type HtmlTarget,
  type PatchOrigin,
  type SourceRange,
} from "./match";
export {
  insertHtml,
  move,
  remove,
  replaceElement,
  setAttr,
  setInnerHtml,
  setStyle,
  setStyleDeclarations,
  setTag,
  setText,
  setTextNode,
  strReplace,
  unwrap,
  wrapText,
  type HtmlOpContext,
  type InsertPosition,
  type StrReplaceOptions,
  type WrapTextOptions,
} from "./ops";
export {
  assertMovable,
  resolveMoveDestination,
  siblingInDirection,
  siblingMoveDestination,
  targetAncestors,
  type MoveDestination,
  type MoveDirection,
  type ResolvedDestination,
} from "./move-target";
export {
  HEADING_LEVELS,
  blockquotePreset,
  buttonPreset,
  escapeHtmlText,
  headingPreset,
  horizontalRulePreset,
  imagePreset,
  listPreset,
  paragraphPreset,
  sectionPreset,
  tablePreset,
  type HeadingLevel,
  type TablePresetOptions,
  type TextPresetOptions,
} from "./insert-presets";
export {
  imageStyleDeclarations,
  imageStyleValue,
  isImageAlign,
  isImageFit,
  mergeImageStyle,
  readImageStyle,
  type ImageAlign,
  type ImageFit,
  type ImageSizeUnit,
  type ImageStyle,
  type ImageStyleInput,
} from "./image-style";
