"use client";
import { ArrowRight, BookOpen, Bot, CalendarDays, Check, CheckCheck, CircleCheck, Clock3, FileText, GitBranch, Hash, Link2, LockKeyhole, Mail, MessageSquare, Mic, MoreHorizontal, Search, ShieldCheck, Sparkles, Star, Users, Video } from "lucide-react";
import { useTranslation } from "react-i18next";
import type { FeaturePageKey } from "./feature-page-catalog";

type Scene = "board" | "focus" | "schedule" | "thread" | "call" | "mail" | "document" | "library" | "flow" | "answer" | "team" | "roles" | "activity" | "overview"; // plan-literal-ok: landing scene key, not a plan code
const FEATURE_SCENES: Record<FeaturePageKey, readonly [Scene, Scene, Scene, Scene]> = {
  dashboard: ["overview", "board", "schedule", "overview"],
  tasks: ["board", "board", "focus", "focus"],
  projects: ["overview", "overview", "board", "thread"],
  today: ["focus", "focus", "activity", "schedule"],
  calendar: ["schedule", "schedule", "schedule", "call"],
  workflows: ["flow", "flow", "team", "flow"], // plan-literal-ok: landing scene key, not a plan code
  meetings: ["call", "schedule", "call", "document"],
  chat: ["thread", "thread", "focus", "flow"],
  email: ["mail", "mail", "mail", "mail"],
  outputs: ["library", "library", "focus", "library"],
  documents: ["document", "document", "focus", "document"],
  approvals: ["flow", "library", "document", "flow"],
  knowledge: ["library", "library", "document", "library"],
  ask: ["answer", "answer", "library", "answer"],
  agents: ["team", "team", "team", "team"], // plan-literal-ok: landing scene key, not a plan code
  automation: ["flow", "flow", "team", "flow"], // plan-literal-ok: landing scene key, not a plan code
  organization: ["team", "team", "roles", "library"], // plan-literal-ok: landing scene key, not a plan code
  audit: ["activity", "activity", "team", "activity"], // plan-literal-ok: landing scene key, not a plan code
};

/** Authored sample interfaces stay legible on phones; these are illustrations, never app controls. */
export function FeatureIllustration({ featureKey, index = 0, decorative = false }: { featureKey: FeaturePageKey; index?: 0 | 1 | 2 | 3; decorative?: boolean }) {
  const { t } = useTranslation();
  const scene = FEATURE_SCENES[featureKey][index];
  const copy = (key: string) => t(`landing.featureVisuals.${key}`);
  const subject = copy("launch");
  const people = <div className="feature-art-people"><span>ML</span><span>HA</span><span>TN</span></div>;
  const statusLabel = (state: "todo" | "in_progress" | "done") => t(`landing.lovable.${state === "done" ? "completed" : state === "in_progress" ? "inProgress" : "todo"}`);
  const row = (key: string, n: number, state: "todo" | "in_progress" | "done" = "in_progress") => <div className="feature-art-row" key={key}><CircleCheck /><span>{copy(key)}</span><small>{statusLabel(state)}</small><span className="feature-art-avatar">{["ML", "HA", "TN"][n]}</span></div>;
  const icon = scene === "thread" ? <Hash /> : scene === "answer" ? <Sparkles /> : scene === "team" ? <ShieldCheck /> : scene === "call" ? <Video /> : scene === "flow" ? <GitBranch /> : scene === "mail" ? <Mail /> : scene === "schedule" ? <CalendarDays /> : <FileText />; // plan-literal-ok: landing scene key, not a plan code
  return <div className="feature-art" data-scene={scene} data-variant={index} role={decorative ? undefined : "img"} aria-hidden={decorative || undefined} aria-label={decorative ? undefined : `${copy("sample")}: ${copy(scene)}`}>
    <div className="feature-art-window" aria-hidden="true">
      <div className="feature-art-bar">{icon}<strong>{subject}</strong><span className="feature-art-dots"><i /><i /><i /></span></div>
      <div className="feature-art-content">
        {scene === "mail" && index > 0 ? <FeatureExampleVariant variant={index === 1 ? "mail-reader" : index === 2 ? "mail-starred" : "mail-connection"} /> : scene === "team" && featureKey === "agents" && index > 0 ? <FeatureExampleVariant variant={index === 1 ? "agent-profile" : index === 2 ? "actor-types" : "agent-scope"} /> : scene === "answer" && index === 3 ? <FeatureExampleVariant variant="read-only" /> : scene === "document" && index === 3 && featureKey === "documents" ? <FeatureExampleVariant variant="document-collaboration" /> : scene === "library" && index === 3 && featureKey === "knowledge" ? <FeatureExampleVariant variant="knowledge-context" /> : scene === "library" && index === 3 && featureKey === "outputs" ? <FeatureExampleVariant variant="output-version" /> : scene === "activity" && index === 3 ? <FeatureExampleVariant variant="audit-record" /> : scene === "flow" && index === 3 && ["workflows", "automation"].includes(featureKey) ? <FeatureExampleVariant variant="rule-draft" /> : scene === "overview" && index === 1 && featureKey === "projects" ? <FeatureExampleVariant variant="project-portfolio" /> : <>{/* plan-literal-ok: landing scene key, not a plan code */}
        {scene === "board" && index === 1 ? <><div className="feature-art-tabs"><span>{copy("list")}</span><span>{copy("board")}</span>{people}</div><div className="feature-art-list">{row("brief", 0, "done")}{row("design", 1)}{row("content", 2, "todo")}</div><div className="feature-art-list-note"><Link2 />{copy("context")}</div></> : scene === "board" && <><div className="feature-art-tabs"><span>{copy("board")}</span><span>{copy("list")}</span>{people}</div><div className="feature-art-board">{(["todo", "in_progress", "done"] as const).map((status, column) => <div key={status}><header><i />{statusLabel(status)}</header>{["brief", "design", "content"].slice(0, column === 2 ? 1 : 2).map((key, n) => <article key={key}><small>UW-{101 + column * 2 + n}</small><strong>{copy(key)}</strong><div className="feature-art-lines"><i /><i /></div><footer><span className="feature-art-avatar">{["ML", "HA", "TN"][column]}</span><MessageSquare />{n + 1}</footer></article>)}</div>)}</div></>}
        {scene === "focus" && <><div className="feature-art-focus-title"><CircleCheck /><strong>{copy("design")}</strong></div><div className="feature-art-properties"><span>{copy("status")}<b>{t("landing.lovable.inProgress")}</b></span><span>{copy("assignee")}<b><span className="feature-art-avatar">ML</span>Minh Linh</b></span><span>{copy("priority")}<b>{t("projects.priority.high")}</b></span></div><div className="feature-art-checklist">{["brief", "design", "content"].map((key, n) => <div key={key}>{n < 2 ? <CheckCheck /> : <CircleCheck />}<span>{copy(key)}</span></div>)}</div><div className="feature-art-attachment"><FileText />{copy("brief")}<Link2 /></div>{index === 3 && <div className="feature-art-inline-comment"><span className="feature-art-avatar">HA</span><span>{copy("messageReply")}</span></div>}</>}
        {scene === "schedule" && index === 1 ? <><div className="feature-art-tabs"><strong>{copy("month")}</strong><span>09 / 2026</span></div><div className="feature-art-month">{Array.from({length: 21}, (_, n) => <div key={n}><span>{n + 7}</span>{[2, 7, 14].includes(n) && <small>{copy(n === 2 ? "sync" : n === 7 ? "review" : "launch")}</small>}</div>)}</div></> : scene === "schedule" && <><div className="feature-art-tabs"><strong>{copy("week")}</strong><span>21 – 25 / 09</span></div><div className="feature-art-calendar">{["mon", "tue", "wed", "thu", "fri"].map((key, n) => <div key={key}><header>{copy(key)}<b>{21 + n}</b></header><div className="feature-art-calendar-cell" /><div className="feature-art-event"><Clock3 /><small>{["09:00", "10:30", "14:00", "11:00", "16:00"][n]}</small><strong>{copy(["sync", "design", "brief", "review", "launch"][n]!)}</strong></div><div className="feature-art-calendar-cell" /></div>)}</div></>}
        {scene === "thread" && <><div className="feature-art-tabs"><Hash /><strong>{copy("projectChannel")}</strong>{people}</div><div className="feature-art-messages"><div><span className="feature-art-avatar">HA</span><div><strong>Hà Anh <small>09:41</small></strong><p>{copy("messageReady")}</p><div className="feature-art-attachment"><FileText />{copy("brief")}<ArrowRight /></div></div></div><div><span className="feature-art-avatar">ML</span><div><strong>Minh Linh <small>09:42</small></strong><p>{copy("messageReply")}</p><span className="feature-art-reaction"><CheckCheck />2</span></div></div></div><div className="feature-art-compose">{copy("message")}<span>@ <Link2 /></span></div></>}
        {scene === "call" && <><div className="feature-art-call"><div className="feature-art-shared"><FileText /><strong>{copy("brief")}</strong><p>{copy("goal")}</p><div className="feature-art-lines"><i /><i /><i /></div></div><div className="feature-art-participants">{["ML", "HA", "TN"].map((name, n) => <div key={name}><span>{name}</span><small>{["Minh Linh", "Hà Anh", "Thảo Nguyên"][n]}</small></div>)}</div></div><div className="feature-art-call-tools"><Mic /><Video /><MessageSquare /><span>{copy("sync")}</span></div></>}
        {scene === "mail" && <div className="feature-art-mail"><aside><Mail /><strong>{copy("inbox")}</strong>{["brief", "review", "launch"].map((key, n) => <div key={key} data-selected={n === 0}><span>{["Hà Anh", "Minh Linh", "Thảo Nguyên"][n]}</span><strong>{copy(key)}</strong><small>09:{41 + n * 3}</small></div>)}</aside><article><small>Hà Anh → Minh Linh</small><strong>{copy("brief")}</strong><p>{copy("messageReady")}</p><div className="feature-art-lines"><i /><i /><i /></div><div className="feature-art-attachment"><FileText />{copy("brief")}<Link2 /></div></article></div>}
        {scene === "document" && <div className="feature-art-document"><div className="feature-art-document-tools"><span>H1</span><b>B</b><em>I</em><Link2 />{people}</div><h4>{copy("brief")}</h4><small>{copy("projectChannel")} / v2</small><h5>{copy("goal")}</h5><p>{copy("goalCopy")}</p><div className="feature-art-lines"><i /><i /></div><div className="feature-art-document-comment"><span className="feature-art-avatar">HA</span><span>{copy("messageReply")}</span></div><h5>{copy("scope")}</h5>{["design", "content"].map(key => <div className="feature-art-document-item" key={key}><Check />{copy(key)}</div>)}</div>}
        {scene === "library" && <><div className="feature-art-search"><Search />{copy("search")}</div><div className="feature-art-library">{["brief", "guide", "notes"].map((key, n) => <div key={key}>{featureKey === "knowledge" ? <BookOpen /> : <FileText />}<strong>{copy(key)}</strong><small>{subject} · v{n + 1}</small><footer><span>{["DOCX", "PDF", "DOCX"][n]}</span><Link2 /></footer></div>)}</div></>}
        {scene === "flow" && <div className="feature-art-flow">{(featureKey === "chat" ? ["messageLabel", "taskLabel", "assignLabel"] : featureKey === "automation" ? ["taskChanged", "conditionMet", "notifyTeam"] : ["request", "review", "handoff"]).map((key, n) => <div key={key}><div className="feature-art-flow-node">{n === 0 ? <FileText /> : n === 1 ? <ShieldCheck /> : <CircleCheck />}<strong>{copy(key)}</strong><small>{["Minh Linh", "Hà Anh", "Thảo Nguyên"][n]}</small></div>{n < 2 && <ArrowRight />}</div>)}<div className="feature-art-flow-context"><GitBranch /><span>{copy(featureKey === "chat" ? "conversionExample" : featureKey === "automation" ? "condition" : "version")}</span></div></div>}
        {scene === "answer" && <div className="feature-art-answer"><div className="feature-art-question"><Search /><span>{copy("question")}</span></div><div className="feature-art-answer-copy"><Sparkles /><div><strong>{copy("answerTitle")}</strong><p>{copy("answerCopy")}</p><div className="feature-art-lines"><i /><i /></div><div className="feature-art-citations"><span><FileText />[S1] {copy("brief")}</span><span><MessageSquare />[S2] {copy("projectChannel")}</span></div></div></div><div className="feature-art-guard"><LockKeyhole />{copy("readOnly")}</div></div>}
        {scene === "team" && <><div className="feature-art-team-head"><ShieldCheck /><strong>{copy("workspace")}</strong>{people}</div><div className="feature-art-team">{["Minh Linh", "Hà Anh", "UNI"].map((name, n) => <div key={name}>{n === 2 ? <span className="feature-art-avatar"><Bot /></span> : <span className="feature-art-avatar">{["ML", "HA"][n]}</span>}<span><strong>{name}</strong><small>{n === 2 ? copy("agentProfile") : copy("member")}</small></span><b>{["owner", "admin", "member"][n]}</b><ShieldCheck /></div>)}</div><div className="feature-art-guard"><LockKeyhole />{copy("permissions")}</div></>}{/* plan-literal-ok: landing scene key, not a plan code */}
        {scene === "roles" && <div className="feature-art-roles">{["organizationLevel", "workspaceLevel"].map(key => <div key={key}><strong><ShieldCheck />{copy(key)}</strong><p>Minh Linh<b>owner</b></p><p>Hà Anh<b>{key === "organizationLevel" ? "member" : "admin"}</b></p></div>)}</div>}
        {scene === "activity" && <div className="feature-art-activity">{["created", "updated", "commented"].map((key, n) => <div key={key}><span className="feature-art-avatar">{["ML", "HA", "TN"][n]}</span><span><strong>{["Minh Linh", "Hà Anh", "Thảo Nguyên"][n]}</strong><p>{copy(key)}</p><small>{copy(["design", "brief", "content"][n]!)}</small></span><time>09:{41 + n * 3}</time></div>)}<div className="feature-art-guard"><ShieldCheck />{copy("history")}</div></div>}
        {scene === "overview" && <><div className="feature-art-tabs"><strong>{subject}</strong>{people}</div><div className="feature-art-overview"><div><span>{copy("progress")}</span><strong>12 / 18</strong><div className="feature-art-progress"><i /></div><small>{copy("sampleProgress")}</small></div><div className="feature-art-bars">{[42, 68, 52, 84, 67].map((height, n) => <div key={n}><i style={{ height: `${height}%` }} /><small>{n + 21}</small></div>)}</div></div><div className="feature-art-overview-list">{row("design", 0)}{row("content", 1, "todo")}</div></>}
        </>}
      </div>
      <div className="feature-art-foot"><Link2 /><span>{copy("context")}</span><MoreHorizontal /></div>
    </div>
  </div>;
}

type ExampleVariant = "mail-reader" | "mail-starred" | "mail-connection" | "agent-profile" | "actor-types" | "agent-scope" | "read-only" | "document-collaboration" | "knowledge-context" | "output-version" | "audit-record" | "rule-draft" | "project-portfolio";

/** Variants demonstrate distinct workflow moments rather than changing only decoration. */
function FeatureExampleVariant({ variant }: { variant: ExampleVariant }) {
  const { t } = useTranslation();
  const copy = (key: string) => t(`landing.featureVisuals.${key}`);
  if (variant === "mail-reader") return <div className="feature-art-reader"><small>Hà Anh → Minh Linh · 09:41</small><h4>{copy("brief")}</h4><p>{copy("messageReady")}</p><div className="feature-art-lines"><i /><i /><i /></div><div className="feature-art-attachment"><FileText />{copy("brief")}<Link2 /></div><div className="feature-art-inline-comment"><Mail /><span>{copy("replyContext")}</span></div></div>;
  if (variant === "mail-starred") return <div className="feature-art-starred"><h4><Star />{copy("starred")}</h4>{["brief", "review"].map((key, n) => <div key={key}><Star /><span><strong>{copy(key)}</strong><small>{n === 0 ? "Hà Anh" : "Minh Linh"}</small><p>{copy(n === 0 ? "messageReady" : "messageReply")}</p></span><time>09:{41 + n * 3}</time></div>)}<div className="feature-art-guard"><Mail />{copy("starredHint")}</div></div>;
  if (variant === "mail-connection") return <div className="feature-art-connection"><div><Mail /><strong>{copy("emailAccount")}</strong><small>team@example.com</small></div><ArrowRight /><div><ShieldCheck /><strong>{copy("workspace")}</strong><small>{copy("configuration")}</small></div><ArrowRight /><div><Mail /><strong>{copy("inbox")}</strong><small>{copy("syncConfigured")}</small></div><div className="feature-art-guard"><LockKeyhole />{copy("connectionScope")}</div></div>;
  if (variant === "agent-profile") return <div className="feature-art-profile"><span className="feature-art-profile-icon"><Bot /></span><h4>UNI</h4><p>{copy("agentProfile")}</p><dl><div><dt>{copy("role")}</dt><dd>member</dd></div><div><dt>{copy("workspace")}</dt><dd>{copy("projectChannel")}</dd></div><div><dt>{copy("profilePurpose")}</dt><dd>{copy("sourceReview")}</dd></div></dl><div className="feature-art-guard"><ShieldCheck />{copy("profileScope")}</div></div>;
  if (variant === "actor-types") return <div className="feature-art-actor-types"><div><Users /><h4>{copy("people")}</h4><span className="feature-art-avatar">ML</span><strong>Minh Linh</strong><span className="feature-art-avatar">HA</span><strong>Hà Anh</strong></div><div><Bot /><h4>{copy("agents")}</h4><span className="feature-art-avatar"><Bot /></span><strong>UNI</strong><small>{copy("agentProfile")}</small></div><p><ShieldCheck />{copy("actorIdentity")}</p></div>;
  if (variant === "agent-scope") return <div className="feature-art-scope"><h4><Bot />{copy("agentFoundation")}</h4><div><FileText /><strong>{copy("agentProfile")}</strong><span>{copy("foundation")}</span></div><div><LockKeyhole /><strong>{copy("permissions")}</strong><span>{copy("configuration")}</span></div><div><GitBranch /><strong>{copy("autonomous")}</strong><span>{copy("roadmap")}</span></div><p>{copy("agentAvailability")}</p></div>;
  if (variant === "read-only") return <div className="feature-art-read-only"><div className="feature-art-read-only-head"><LockKeyhole /><h4>{copy("readOnlyTitle")}</h4></div><div className="feature-art-read-path"><FileText /><span>{copy("brief")}</span><ArrowRight /><Sparkles /><span>{copy("answerTitle")}</span></div><div className="feature-art-permission-row"><Check />{copy("readSources")}</div><div className="feature-art-permission-row"><LockKeyhole />{copy("noChanges")}</div><p>{copy("humanDecision")}</p></div>;
  if (variant === "document-collaboration") return <div className="feature-art-collaboration"><div className="feature-art-document-tools"><span>H1</span><b>B</b><em>I</em><Link2 /><span className="feature-art-avatar">ML</span><span className="feature-art-avatar">HA</span></div><h4>{copy("brief")}</h4><div className="feature-art-edit-block"><span className="feature-art-avatar">ML</span><p>{copy("goalCopy")}</p></div><div className="feature-art-edit-block"><span className="feature-art-avatar">HA</span><p>{copy("scopeCopy")}</p></div><div className="feature-art-document-comment"><MessageSquare /><span>{copy("messageReply")}</span></div><div className="feature-art-guard"><FileText />{copy("editorDirection")}</div></div>;
  if (variant === "knowledge-context") return <div className="feature-art-context-map"><h4>{copy("sourcesContext")}</h4><div><BookOpen /><strong>{copy("guide")}</strong><small>{copy("topic")}</small></div><ArrowRight /><div><FileText /><strong>{copy("brief")}</strong><small>{copy("sourceDocument")}</small></div><ArrowRight /><div><CircleCheck /><strong>{copy("design")}</strong><small>{copy("relatedTask")}</small></div><div className="feature-art-guard"><LockKeyhole />{copy("knowledgeDirection")}</div></div>;
  if (variant === "rule-draft") return <div className="feature-art-rule-draft"><header><GitBranch /><h4>{copy("ruleExample")}</h4><span>draft</span></header><dl><div><dt>{copy("when")}</dt><dd>{copy("taskChanged")}</dd></div><div><dt>{copy("if")}</dt><dd>status = done</dd></div><div><dt>{copy("then")}</dt><dd>{copy("notifyTeam")}</dd></div></dl><div className="feature-art-guard"><LockKeyhole />{copy("roadmapRule")}</div></div>;
  if (variant === "output-version") return <div className="feature-art-profile"><span className="feature-art-profile-icon"><FileText /></span><h4>{copy("brief")}</h4><dl><div><dt>{copy("versionLabel")}</dt><dd>v1 <ArrowRight /> v2</dd></div><div><dt>{copy("assignee")}</dt><dd>Minh Linh</dd></div><div><dt>{copy("relatedTask")}</dt><dd>{copy("design")}</dd></div></dl><div className="feature-art-guard"><Link2 />{copy("outputDirection")}</div></div>;
  if (variant === "audit-record") return <div className="feature-art-profile"><span className="feature-art-profile-icon"><ShieldCheck /></span><h4>{copy("recordDetail")}</h4><dl><div><dt>{copy("actor")}</dt><dd>Minh Linh</dd></div><div><dt>{copy("event")}</dt><dd>task.updated</dd></div><div><dt>{copy("time")}</dt><dd>24/09/2026 · 09:41</dd></div><div><dt>{copy("workspace")}</dt><dd>{copy("projectChannel")}</dd></div></dl><div className="feature-art-guard"><LockKeyhole />{copy("appendOnly")}</div></div>;
  return <div className="feature-art-portfolio">{["launch", "onboarding", "operations"].map((key, n) => <div key={key}><strong>{copy(key)}</strong><span>{t("projects.status.in_progress")}</span><div><CircleCheck /><small>{["12 / 18", "4 / 10", "7 / 12"][n]}</small><span className="feature-art-avatar">{["ML", "HA", "TN"][n]}</span></div></div>)}<div className="feature-art-guard"><FileText />{copy("sampleProgress")}</div></div>;
}
