"use client";
import { ArrowDownToLine, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Grid2X2, Link, List, MoreHorizontal, Plus, Search, Upload, Users, Video } from "lucide-react";
import { LovableControl, LovablePageHeading, usePreviewLabels } from "./lovable-frame";

export function LovablePeople() {
  const copy = usePreviewLabels();
  return <div className="lovable-page"><LovablePageHeading title={copy("peopleDirectory")} subtitle={copy("peopleSub")}><LovableControl><Upload />{copy("import")}</LovableControl><LovableControl><ArrowDownToLine />{copy("export")}</LovableControl><LovableControl primary><Plus />{copy("addPerson")}</LovableControl></LovablePageHeading><div className="lovable-list-filter"><div className="lovable-search-field"><Search />{copy("searchPeople")}</div>{["department", "role", "location", "moreFilters"].map(key => <LovableControl key={key}>{copy(key)}<ChevronDown /></LovableControl>)}<LovableControl><Grid2X2 />{copy("grid")}<List />{copy("list")}</LovableControl></div><div className="lovable-project-tabs">{["allPeople", "teams", "departments", "positions", "skills", "orgChart"].map((key, i) => <span key={key} data-active={i === 0}>{copy(key)}</span>)}</div><div className="lovable-people-grid">{["Minh Linh", "Hoàng Anh", "Thanh Ngân", "Lê Tùng"].map((name, i) => <section className="lovable-card" key={name}><span className="action-avatar" data-person={["ML","HA","TN","LT"][i]}>{["ML","HA","TN","LT"][i]}</span><h3>{name}</h3><p>{["owner","admin","member","member"][i]}</p><div className="lovable-key-value"><span>{copy("department")}</span><strong>{copy(i > 1 ? "operations" : "productTeam")}</strong></div><footer><Users />General<MoreHorizontal /></footer></section>)}</div></div>;
}


export function LovableMeetings() {
  const copy = usePreviewLabels();
  return <div className="lovable-meetings-page"><div className="lovable-page"><LovablePageHeading title={copy("meetings")} subtitle={copy("meetingsSub")}><LovableControl primary><Video />{copy("startMeeting")}</LovableControl><LovableControl><CalendarDays />{copy("schedule")}</LovableControl><LovableControl><Link />{copy("joinCode")}</LovableControl><LovableControl><Clock3 />{copy("history")}</LovableControl></LovablePageHeading><div className="lovable-meeting-totals">{["today", "ongoing", "recordings", "aiSummary"].map((key, i) => <span key={key}>{copy(key)} <strong>{[2,0,1,0][i]}</strong></span>)}</div><div className="lovable-list-filter"><div className="lovable-view-tabs">{["all", "upcoming", "ongoing", "ended"].map((key, i) => <span key={key} data-active={i === 0}>{copy(key)}</span>)}</div><div className="lovable-search-field"><Search />{copy("searchMeetings")}</div><LovableControl>09/24/2026<CalendarDays /></LovableControl></div><div className="lovable-meeting-list">{["sync", "designReview", "launchPlan", "weeklyReport", "onboarding"].map((key, i) => <div key={key}><span className="lovable-file-icon"><CalendarDays /></span><div><strong>{copy(key)}</strong><p><Clock3 />{["09:30", "11:00", "14:00", "15:30", "16:00"][i]} · 24/09 · 30 {copy("minutes")}</p></div><span className="lovable-tag">{copy(i < 2 ? "upcoming" : "ended")}</span><LovableControl>{copy(i < 2 ? "join" : "review")}</LovableControl><MoreHorizontal /></div>)}</div></div><aside className="lovable-meetings-calendar"><header><strong>{copy("month")}</strong><ChevronLeft /><ChevronRight /></header><div className="lovable-mini-calendar">{Array.from({ length: 35 }, (_, i) => <span key={i} data-selected={i === 24}>{i > 0 && i <= 30 ? i : ""}</span>)}</div><h3>{copy("upcoming")}</h3><p>{copy("sync")}<small>09:30 – 10:00</small></p></aside></div>;
}
