.PHONY: help doctor dev setup start stop check db-up db-down db-reset worktree-env setup-worktree start-worktree stop-worktree check-worktree server web build test test-go test-fe e2e migrate-up migrate-down sqlc clean

# ---------- Env selection ----------
# The main checkout uses .env; a git worktree uses .env.worktree (generated by
# `make worktree-env`) so it gets its own database and ports. ENV_FILE picks
# whichever exists, main first. Every target below reads this file.
MAIN_ENV_FILE ?= .env
WORKTREE_ENV_FILE ?= .env.worktree
ENV_FILE ?= $(if $(wildcard $(MAIN_ENV_FILE)),$(MAIN_ENV_FILE),$(if $(wildcard $(WORKTREE_ENV_FILE)),$(WORKTREE_ENV_FILE),$(MAIN_ENV_FILE)))

ifneq ($(wildcard $(ENV_FILE)),)
include $(ENV_FILE)
endif

POSTGRES_DB ?= uniwork
POSTGRES_USER ?= uniwork
POSTGRES_PASSWORD ?= uniwork
POSTGRES_PORT ?= 5432
PORT ?= 8080
ENABLE_SWAGGER ?= true
FRONTEND_PORT ?= 3000
FRONTEND_ORIGIN ?= http://localhost:$(FRONTEND_PORT)
DATABASE_URL ?= postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@localhost:$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable
TEST_DATABASE_URL ?= postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@localhost:$(POSTGRES_PORT)/$(POSTGRES_DB)_test?sslmode=disable
REDIS_TEST_URL ?= redis://localhost:6379/15
NEXT_PUBLIC_API_URL ?= http://localhost:$(PORT)
NEXT_PUBLIC_WS_URL ?= ws://localhost:$(PORT)
NEXT_PUBLIC_APP_URL ?= $(FRONTEND_ORIGIN)
E2E_BASE_URL ?= $(FRONTEND_ORIGIN)

export

COMPOSE := docker compose

define REQUIRE_ENV
	@if [ ! -f "$(ENV_FILE)" ]; then \
		echo "Missing env file: $(ENV_FILE)"; \
		echo "Create .env from .env.example, or run 'make worktree-env' and use .env.worktree."; \
		exit 1; \
	fi
endef

.DEFAULT_GOAL := help

##@ Help

help: ## Show available make targets and common local workflows
	@awk 'BEGIN {FS = ":.*## "; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nQuick start:\n  \033[36mmake dev\033[0m          Bootstrap this checkout and start everything\n  \033[36mmake check\033[0m        Run the full local verification pipeline\n\nCheckout modes:\n  Main checkout uses \033[36m.env\033[0m\n  Worktrees use \033[36m.env.worktree\033[0m (generate with \033[36mmake worktree-env\033[0m)\n\n"} \
		/^##@/ {printf "\n\033[1m%s\033[0m\n", substr($$0, 5); next} \
		/^[a-zA-Z0-9_.-]+:.*## / {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

##@ One-click

doctor: ## Check the local toolchain and repo wiring against what this repo pins
	@bash scripts/doctor.sh

dev: ## Bootstrap this checkout end-to-end: env file, deps, DB, migrations, both services
	@bash scripts/dev.sh

setup: ## Prepare the current checkout from its env file: install deps, ensure DB, run migrations
	$(REQUIRE_ENV)
	@echo "==> Using env file: $(ENV_FILE)"
	pnpm install
	@bash scripts/ensure-postgres.sh "$(ENV_FILE)"
	cd server && go run ./cmd/migrate up
	@echo "✓ Setup complete. Git hooks are wired (.githooks). Run 'make start' to launch the app."

start: ## Start backend and frontend for the current checkout (migrates first)
	$(REQUIRE_ENV)
	@echo "Using env file: $(ENV_FILE)"
	@echo "Backend:  http://localhost:$(PORT)"
	@echo "Frontend: http://localhost:$(FRONTEND_PORT)"
	@if [ "$(ENABLE_SWAGGER)" = "true" ] || [ "$(ENABLE_SWAGGER)" = "1" ] || [ "$(ENABLE_SWAGGER)" = "yes" ]; then \
		echo "Swagger:  http://localhost:$(PORT)/swagger/index.html"; \
	fi
	@bash scripts/ensure-postgres.sh "$(ENV_FILE)"
	cd server && go run ./cmd/migrate up
	@trap 'kill 0' EXIT; \
		(cd server && go run ./cmd/server) & \
		pnpm --filter @uniwork/web dev & \
		wait

stop: ## Stop the backend and frontend processes of the current checkout (DB keeps running)
	$(REQUIRE_ENV)
	@-lsof -ti:$(PORT) | xargs kill -9 2>/dev/null
	@-lsof -ti:$(FRONTEND_PORT) | xargs kill -9 2>/dev/null
	@echo "✓ App processes stopped. Shared PostgreSQL/Redis are still running."

check: ## Typecheck, lint, TS tests, Go tests, then Playwright E2E for the current checkout
	$(REQUIRE_ENV)
	@ENV_FILE="$(ENV_FILE)" bash scripts/check.sh

##@ Worktrees

worktree-env: ## Generate .env.worktree with a unique database and ports for this worktree
	@bash scripts/init-worktree-env.sh $(WORKTREE_ENV_FILE)

setup-worktree: ## Ensure .env.worktree exists, then prepare this worktree
	@if [ ! -f "$(WORKTREE_ENV_FILE)" ]; then bash scripts/init-worktree-env.sh $(WORKTREE_ENV_FILE); fi
	@$(MAKE) setup ENV_FILE=$(WORKTREE_ENV_FILE)

start-worktree: ## Start this worktree using .env.worktree
	@$(MAKE) start ENV_FILE=$(WORKTREE_ENV_FILE)

stop-worktree: ## Stop this worktree's backend and frontend
	@$(MAKE) stop ENV_FILE=$(WORKTREE_ENV_FILE)

check-worktree: ## Run the full verification pipeline for this worktree
	@ENV_FILE=$(WORKTREE_ENV_FILE) bash scripts/check.sh

##@ Individual commands

server: ## Run only the Go server for the current checkout
	$(REQUIRE_ENV)
	@bash scripts/ensure-postgres.sh "$(ENV_FILE)"
	cd server && go run ./cmd/server

web: ## Run only the Next.js dev server
	pnpm --filter @uniwork/web dev

VERSION ?= $(shell git describe --tags --match 'v[0-9]*' --always --dirty 2>/dev/null || echo dev)
COMMIT  ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)

build: ## Build the server and migrate binaries into server/bin
	cd server && go build -ldflags "-X main.version=$(VERSION) -X main.commit=$(COMMIT)" -o bin/server ./cmd/server
	cd server && go build -o bin/migrate ./cmd/migrate

test: test-go test-fe ## Go tests then TS tests

test-go: ## Go: gofmt, vet, staticcheck, test -race (ensures the test DB and migrations first)
	$(REQUIRE_ENV)
	@bash scripts/ensure-postgres.sh "$(ENV_FILE)"
	cd server && go run ./cmd/migrate up
	bash scripts/test-go.sh --race

test-fe: ## TypeScript unit tests through Turborepo
	pnpm test

e2e: ## Playwright E2E against E2E_BASE_URL (needs a running app: make dev / make start)
	pnpm --filter @uniwork/e2e exec playwright install chromium
	pnpm --filter @uniwork/e2e test

##@ Database

db-up: ## Start the shared PostgreSQL and Redis containers used by main and worktrees
	@$(COMPOSE) up -d postgres postgres-test redis

db-down: ## Stop the shared containers without removing their volumes
	@$(COMPOSE) down

db-reset: ## Drop and recreate the current env's database, then re-run all migrations
	$(REQUIRE_ENV)
	@case "$(DATABASE_URL)" in \
		*@localhost:*|*@localhost/*|*@127.0.0.1:*|*@127.0.0.1/*) ;; \
		*) echo "Refusing to reset: DATABASE_URL points at a remote host."; exit 1 ;; \
	esac
	@bash scripts/ensure-postgres.sh "$(ENV_FILE)"
	@$(COMPOSE) exec -T postgres psql -U $(POSTGRES_USER) -d postgres -v ON_ERROR_STOP=1 \
		-c "DROP DATABASE IF EXISTS \"$(POSTGRES_DB)\" WITH (FORCE);" \
		-c "CREATE DATABASE \"$(POSTGRES_DB)\";"
	cd server && go run ./cmd/migrate up
	@echo "✓ Database '$(POSTGRES_DB)' reset."

migrate-up: ## Create the DB if needed, then apply migrations
	$(REQUIRE_ENV)
	@bash scripts/ensure-postgres.sh "$(ENV_FILE)"
	cd server && go run ./cmd/migrate up

migrate-down: ## Roll back the most recent migration
	$(REQUIRE_ENV)
	cd server && go run ./cmd/migrate down

sqlc: ## Regenerate sqlc code after editing server/pkg/db/queries
	cd server && go run github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1 generate

##@ Cleanup

clean: ## Remove build caches, generated binaries and temp files
	rm -rf server/bin
	rm -rf apps/*/.next apps/*/out packages/*/dist
	rm -rf .turbo apps/*/.turbo packages/*/.turbo
	rm -rf apps/*/*.tsbuildinfo packages/*/*.tsbuildinfo
	@echo "✓ Clean complete."
