"use client";

import { useEffect, useId, useMemo, useState, type KeyboardEvent } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@uniwork/ui/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@uniwork/ui/components/ui/dialog";
import { Input } from "@uniwork/ui/components/ui/input";
import { Label } from "@uniwork/ui/components/ui/label";
import { compileInlineEquation, type InlineEquationAttrs } from "./math";

export interface EquationDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Read-only documents keep the field visible but block Insert. */
  readOnly?: boolean;
  /** The caller inserts the compiled equation and closes the dialog. */
  onInsert: (latex: string) => void;
}

/**
 * Insert > Equation dialog (task A11): LaTeX input with a live MathML preview.
 * Insert compiles to the vendored docInlineMath node, so the equation saves as
 * a Run.math <m:oMath> through the existing save path (no new engine op).
 */
export function EquationDialog({ open, onOpenChange, readOnly = false, onInsert }: EquationDialogProps) {
  const { t } = useTranslation();
  const latexId = useId();
  const errorId = useId();
  const [latex, setLatex] = useState("");

  useEffect(() => {
    if (open) setLatex("");
  }, [open]);

  const preview = useMemo<InlineEquationAttrs | "invalid" | null>(() => {
    if (latex.trim() === "") return null;
    try {
      return compileInlineEquation(latex);
    } catch {
      return "invalid";
    }
  }, [latex]);

  const valid = preview !== null && preview !== "invalid";

  const submit = (): void => {
    if (!valid || readOnly) return;
    onInsert(latex);
  };

  const onKeyDown = (event: KeyboardEvent<HTMLDivElement>): void => {
    if (event.key === "Escape") {
      event.preventDefault();
      onOpenChange(false);
      return;
    }
    // Enter submits from the text field; buttons keep their own activation.
    if (event.key === "Enter" && event.target instanceof HTMLInputElement) {
      event.preventDefault();
      submit();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent data-testid="docx-equation-dialog" className="gap-3" closeLabel={t("common.close")} onKeyDown={onKeyDown}>
        <DialogHeader className="gap-1">
          <DialogTitle>{t("office.docx.equation.title")}</DialogTitle>
          <DialogDescription>{t("office.docx.equation.description")}</DialogDescription>
        </DialogHeader>
        <div className="grid gap-3">
          <div className="grid gap-1.5">
            <Label htmlFor={latexId}>{t("office.docx.equation.latex")}</Label>
            <Input
              id={latexId}
              data-testid="docx-equation-latex"
              value={latex}
              disabled={readOnly}
              placeholder={t("office.docx.equation.placeholder")}
              aria-invalid={preview === "invalid" || undefined}
              aria-describedby={preview === "invalid" ? errorId : undefined}
              onChange={(event) => setLatex(event.target.value)}
            />
          </div>
          <div className="grid gap-1.5">
            <span className="text-label text-muted-foreground">{t("office.docx.equation.preview")}</span>
            <div
              className="flex min-h-16 items-center justify-center overflow-x-auto rounded-md border border-border bg-muted/40 px-2 py-1"
              data-testid="docx-equation-preview"
            >
              {preview === null ? <span className="text-caption text-muted-foreground">{t("office.docx.equation.previewEmpty")}</span> : null}
              {preview === "invalid" ? (
                <span id={errorId} role="alert" className="text-caption text-destructive">
                  {t("office.docx.equation.invalid")}
                </span>
              ) : null}
              {preview !== null && preview !== "invalid" ? (
                // The markup is generated by insert/math from our own escaped
                // emitter; no document/user HTML enters this string.
                <span className="text-body" dangerouslySetInnerHTML={{ __html: preview.mathml }} />
              ) : null}
            </div>
          </div>
        </div>
        <DialogFooter className="flex-row items-center justify-end">
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            {t("common.cancel")}
          </Button>
          <Button type="button" disabled={!valid || readOnly} onClick={submit} data-testid="docx-equation-insert">
            {t("office.docx.equation.insert")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
