import type { Metadata, Viewport } from "next";
import { Inter, Source_Serif_4 } from "next/font/google";
import "./globals.css";
// Before `metadata` is evaluated: it reads the public origin from the runtime
// config, and this module is the only place that config is populated.
import "../platform/runtime-config";
import { runtimeConfig } from "@uniwork/core/runtime-config";
import { resolveRequestLocale } from "../platform/locale-server";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin", "vietnamese"], variable: "--font-inter", display: "swap" });
// Serif biên tập cho headline onboarding; cần italic cho <em> trong h1.
const sourceSerif = Source_Serif_4({
  subsets: ["latin", "vietnamese"],
  style: ["normal", "italic"],
  variable: "--font-source-serif",
  display: "swap",
});

const DESCRIPTION =
  "Work OS thuần AI cho đội ngũ Việt: công việc, cuộc họp, tài liệu và quy trình " +
  "do người và AI cùng sở hữu, trong một không gian.";

/**
 * Every URL-based metadata field resolves against this, so a malformed value
 * would silently ship Open Graph tags pointing at nothing. `new URL` throws
 * ERR_INVALID_URL with no mention of which variable is wrong; this says it.
 */
function siteOrigin(): URL {
  const raw = runtimeConfig().appUrl;
  try {
    return new URL(raw);
  } catch {
    throw new Error(
      `NEXT_PUBLIC_APP_URL must be an absolute origin, got ${JSON.stringify(raw)}. ` +
        "Open Graph and icon URLs are resolved against it, and it is inlined at " +
        "build time — see apps/web/Dockerfile.",
    );
  }
}

/**
 * Paints the browser chrome around the page: the iOS Safari toolbars and the
 * Android Chrome address bar. Matched to the page canvas in each theme so the
 * chrome reads as part of the page rather than a coloured band above it. The
 * manifest's single `theme_color` cannot vary by theme and stays the brand hue,
 * which is what the installed app shows in the task switcher.
 */
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafafa" },
    { media: "(prefers-color-scheme: dark)", color: "#111113" },
  ],
};

/**
 * `icon.svg`, `favicon.ico`, `apple-icon.png` and `opengraph-image.png` live in
 * this directory and Next wires them up by file convention — there is no
 * `icons` block here on purpose. All four are generated by `pnpm brand:build`.
 */
export const metadata: Metadata = {
  metadataBase: siteOrigin(),
  title: { default: "UniWork", template: "%s · UniWork" },
  description: DESCRIPTION,
  applicationName: "UniWork",
  openGraph: {
    type: "website",
    siteName: "UniWork",
    title: "UniWork",
    description: DESCRIPTION,
    locale: "vi_VN",
  },
  twitter: { card: "summary_large_image", title: "UniWork", description: DESCRIPTION },
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await resolveRequestLocale();
  // English only: keep `en.json` off the shared client chunk (bundle-budget).
  const initialDictionary =
    locale === "en" ? (await import("@uniwork/core/i18n/locales/en.json")).default : undefined;
  return (
    <html lang={locale} suppressHydrationWarning className={`${inter.variable} ${sourceSerif.variable}`}>
      <body className="font-sans">
        <Providers initialLocale={locale} initialDictionary={initialDictionary}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
