import type { MetadataRoute } from "next";

/**
 * PWA manifest. The icons are generated by `pnpm brand:build`; the maskable one
 * is a separate drawing rather than the same file re-tagged, because launchers
 * crop up to 20% off every edge and the standard tile's glyph would lose its
 * heads.
 *
 * `theme_color` is the flat brand hue, not the logo gradient: it paints the
 * Android status bar, which is product chrome.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "UniWork",
    short_name: "UniWork",
    description: "Work OS thuần AI cho đội ngũ Việt.",
    start_url: "/",
    display: "standalone",
    background_color: "#fafafa",
    theme_color: "#7612fa",
    lang: "vi",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
