// Generated by scripts/brand/build-assets.mjs. Do not edit.
export const OG_IMAGES = {
  root: { url: "/opengraph-image.png?v=1896c38701", width: 1200, height: 630, alt: "UniWork: Your team. One workspace. A task owned together by Maya and UNI, an AI teammate, above a live meeting and an Ask UNI prompt." },
  meetingInvite: { url: "/brand/og/meeting-invite.png?v=2f0f888b00", width: 1200, height: 630, alt: "UniWork meeting invitation: join the meeting from your browser, with UNI taking the notes." },
  workspaceInvite: { url: "/brand/og/workspace-invite.png?v=24a581bd47", width: 1200, height: 630, alt: "UniWork workspace invitation: join a team of people and UNI, an AI teammate." },
  sharedDocument: { url: "/brand/og/shared-document.png?v=3419801613", width: 1200, height: 630, alt: "A document shared from UniWork, written by Maya and UNI, open to read in the browser." },
} as const;
