// DOC-003 lab host surface (UNI-667). GENERATED from the pinned GenOffice source; do not hand-edit.
//
// Every window.<api>.<method> the six renderers read, frozen at
// genoffice@09485f884dc845cf3bf27fb7edfe489f9d457aad. The renderer transform
// (scripts/office-g0/build-renderers.mjs) rewrites each of these reads onto the imported
// host, and the host adapter turns any method it does not implement into a throwing call,
// so an unsupported access is loud instead of a silent null.

export const PINNED_SOURCE_COMMIT = '09485f884dc845cf3bf27fb7edfe489f9d457aad';

/** window.<global>.<method> arrays per app, exactly as the renderers read them. */
export const HOST_SURFACE = {
  "docs": {
    "desktop": [
      "addAttachmentPaths",
      "addPastedImage",
      "aiGenerateImage",
      "aiGskLogin",
      "aiGskStatus",
      "aiStream",
      "aiStreamCancel",
      "consumeAiDocContent",
      "consumeHeadlessExport",
      "consumeNewBlankDoc",
      "consumePendingOpenDocx",
      "convertAltChunkHtml",
      "copyImageToClipboard",
      "createDocument",
      "discardDocPasswordIntents",
      "docPasswordIntentRevision",
      "exportHtml",
      "exportPdf",
      "fetchImage",
      "focusDocsTab",
      "getAiPanelPrefs",
      "getAiSettings",
      "getLanguage",
      "getPathForFile",
      "getRecentFiles",
      "getTheme",
      "headlessExportDone",
      "imageSearch",
      "listDocsTabs",
      "onAiPanelPrefsChanged",
      "onAiStream",
      "onChromePressed",
      "onCloseCheck",
      "onCloseSaveRequest",
      "onLanguageChanged",
      "onMenuCommand",
      "onOpenDocx",
      "onRenamedDocx",
      "onTeardown",
      "onThemeChanged",
      "onViewImage",
      "onZoteroRequest",
      "openDocx",
      "openDocxDecrypt",
      "openDocxPath",
      "openNewTab",
      "pickAttachments",
      "pickExportImagesTarget",
      "pickImage",
      "print",
      "printPdfBuffer",
      "readAttachment",
      "readAttachmentImage",
      "reportCloseCheck",
      "reportCloseSaveResult",
      "reportViewMenuState",
      "respellKick",
      "respondToZotero",
      "saveDocx",
      "saveDocxAs",
      "saveDocxNew",
      "saveDocxTo",
      "saveImageAs",
      "saveMergedPdf",
      "setDocPassword",
      "spellDiag",
      "takeExportPdf",
      "webSearch",
      "writeExportImage",
      "writeRecoveryCopy",
      "zoteroCommand"
    ],
    "projectApi": [],
    "filesPaneApi": []
  },
  "markdown": {
    "markdownApi": [
      "aiGenerateImage",
      "aiGskStatus",
      "aiStream",
      "aiStreamCancel",
      "consumeHeadlessExport",
      "consumePending",
      "exportDocx",
      "exportPdf",
      "fetchImage",
      "getAiPanelPrefs",
      "getAiSettings",
      "getLanguage",
      "getTheme",
      "headlessExportDone",
      "imageSearch",
      "onAiPanelPrefsChanged",
      "onAiStream",
      "onCloseSaveRequest",
      "onExportRequest",
      "onFileRenamed",
      "onLanguageChanged",
      "onPrintRequest",
      "onReadTextRequest",
      "onSaveRequest",
      "onThemeChanged",
      "onViewImage",
      "pickImage",
      "readFile",
      "readImage",
      "save",
      "saveImage",
      "saveImageAs",
      "sendCloseSaveResult",
      "sendReadTextResult",
      "sendSaveRequestAck",
      "setDirty",
      "webSearch"
    ],
    "projectApi": [
      "appendChat",
      "rebindChat"
    ],
    "filesPaneApi": []
  },
  "html": {
    "htmlApi": [
      "addAttachmentPaths",
      "addPastedImage",
      "aiStream",
      "aiStreamCancel",
      "consumeHeadlessExport",
      "consumePending",
      "exportDocx",
      "exportHtml",
      "exportPdf",
      "fetchImage",
      "getAiPanelPrefs",
      "getAiSettings",
      "getLanguage",
      "getPathForFile",
      "getPreviewInfo",
      "getTheme",
      "headlessExportDone",
      "onAiPanelPrefsChanged",
      "onAiStream",
      "onCloseSaveRequest",
      "onExportRequest",
      "onFileRenamed",
      "onLanguageChanged",
      "onReadTextRequest",
      "onSaveRequest",
      "onThemeChanged",
      "pickAttachments",
      "pickImage",
      "presentInNewTab",
      "readAttachment",
      "readAttachmentImage",
      "readFile",
      "readImage",
      "save",
      "saveImage",
      "sendCloseSaveResult",
      "sendReadTextResult",
      "sendSaveRequestAck",
      "setDirty",
      "setPresentFullScreen",
      "setProvisionalTitle",
      "updatePreview",
      "webSearch"
    ],
    "projectApi": [
      "appendChat",
      "rebindChat"
    ],
    "filesPaneApi": []
  },
  "pdf": {
    "pdfApi": [
      "addSavedSignature",
      "aiStream",
      "aiStreamCancel",
      "autoRename",
      "canDrawText",
      "consumePending",
      "convertOffice",
      "createDocument",
      "cropPages",
      "exportImages",
      "extractPages",
      "fetchImage",
      "generateImage",
      "getAiPanelPrefs",
      "getAiSettings",
      "getLanguage",
      "getTheme",
      "getUsername",
      "gskStatus",
      "imageSearch",
      "insertBlankPage",
      "insertPdf",
      "isUntitled",
      "listEditFonts",
      "listPageImages",
      "listSavedSignatures",
      "listStaticFormFills",
      "mergePages",
      "mergePdf",
      "ocrPage",
      "onAiPanelPrefsChanged",
      "onAiStream",
      "onCloseSaveRequest",
      "onFileRenamed",
      "onLanguageChanged",
      "onPrintRequest",
      "onSaveAsFlow",
      "onSaveAsRequest",
      "onThemeChanged",
      "pageImagePng",
      "pagePreviewPng",
      "readFile",
      "removeSavedSignature",
      "replacePages",
      "save",
      "sendCloseSaveResult",
      "sendSaveAsResult",
      "setDirty",
      "setPageSize",
      "splitPages",
      "splitPdf",
      "validateTextEdits"
    ],
    "projectApi": [],
    "filesPaneApi": []
  },
  "sheets": {
    "desktopApi": [
      "addAttachmentPaths",
      "addPastedImage",
      "aiGskLogin",
      "aiGskStatus",
      "aiStream",
      "aiStreamCancel",
      "autoRenameWorkbook",
      "captureScreenSource",
      "captureScreenSources",
      "closeWorkbook",
      "confirmCsvSave",
      "consumeHeadlessExport",
      "consumeNewBlankWorkbook",
      "createDocument",
      "exportCsv",
      "exportPdf",
      "fetchImage",
      "generateImage",
      "getAiPanelPrefs",
      "getAiSettings",
      "getLanguage",
      "getPathForFile",
      "getTheme",
      "hasQueuedWorkbook",
      "headlessExportDone",
      "imageSearch",
      "notifyPendingEdits",
      "onAiPanelPrefsChanged",
      "onAiStream",
      "onChromePressed",
      "onCloseSaveRequest",
      "onLanguageChanged",
      "onMenuAction",
      "onRecoveryPrompt",
      "onThemeChanged",
      "onWorkbookRenamed",
      "openExternal",
      "openWorkbooksForMerge",
      "pickAttachments",
      "printWorkbook",
      "readAttachment",
      "readAttachmentImage",
      "readLocalImage",
      "readPivotDefinition",
      "readWorkbookFormulas",
      "readWorkbookMedia",
      "readWorkbookRange",
      "recalcWorkbook",
      "replyRecoveryPrompt",
      "reportCloseSaveResult",
      "saveWorkbookEdits",
      "selectWorkbook",
      "selectWorkbooksForMerge",
      "webSearch",
      "writeWorkbookRecovery"
    ],
    "projectApi": [],
    "filesPaneApi": []
  },
  "slides": {
    "desktop": [
      "addAttachmentPaths",
      "addPastedImage",
      "getPathForFile",
      "pickAttachments",
      "readAttachment",
      "readAttachmentImage"
    ],
    "slidesApi": [
      "addBlankSlide",
      "addChart",
      "addComment",
      "addElement",
      "addImageBytes",
      "addInk",
      "addMediaBytes",
      "addSection",
      "addSlide",
      "addSlideWithLayout",
      "addSmartArt",
      "addTable",
      "aiGskLogin",
      "aiGskStatus",
      "aiLogRunFailure",
      "aiSnapshotRestore",
      "aiStream",
      "aiStreamCancel",
      "analyzeMedia",
      "applyEditScript",
      "applyHeaderFooter",
      "applyTheme",
      "applyTxn",
      "audienceNav",
      "audienceReady",
      "batchEditTransform",
      "beginHistoryBatch",
      "changeShape",
      "clipboardExternal",
      "clipboardProbe",
      "cloudGenStatus",
      "cloudGeneratePage",
      "consumeHeadlessExport",
      "consumePendingOpen",
      "copyElements",
      "copySlide",
      "deleteComment",
      "deleteElement",
      "deleteSlide",
      "duplicateElements",
      "editBackground",
      "editChart",
      "editConnectorEndpoints",
      "editFill",
      "editImageFill",
      "editPictureOpacity",
      "editPictureSrcRect",
      "editStroke",
      "editTableCell",
      "editTableStyle",
      "editText",
      "editTransform",
      "endHistoryBatch",
      "exportImages",
      "exportPdf",
      "findReplace",
      "flipElements",
      "fontCatalog",
      "fontDownload",
      "fontInstallLocal",
      "fontMissing",
      "generateImage",
      "getAiPanelPrefs",
      "getAiSettings",
      "getAnimations",
      "getChartColorSchemes",
      "getChartData",
      "getComments",
      "getHeaderFooter",
      "getLanguage",
      "getLayouts",
      "getLink",
      "getMediaData",
      "getNotes",
      "getRecentFiles",
      "getRenderSlides",
      "getRunLinks",
      "getSections",
      "getShapeKeys",
      "getSlideLinks",
      "getTheme",
      "getTransition",
      "groupElements",
      "hasSlideClipboard",
      "headlessExportDone",
      "imageSearch",
      "insertImage",
      "insertImageUrl",
      "insertMedia",
      "insertModel3d",
      "isDirty",
      "landGeneratedPages",
      "listStyleTemplates",
      "loadStyleTemplate",
      "localGeneratePage",
      "masterClose",
      "masterDeleteElement",
      "masterEditFill",
      "masterEditStroke",
      "masterEditText",
      "masterEditTransform",
      "masterEnter",
      "masterOpen",
      "moveSection",
      "moveSlide",
      "nativeClipboard",
      "newBlank",
      "onAiPanelPrefsChanged",
      "onAiStream",
      "onAudienceNav",
      "onCloseSaveRequest",
      "onDeckChanged",
      "onFontsChanged",
      "onHistoryChanged",
      "onLanguageChanged",
      "onMenuCommand",
      "onOpened",
      "onRenamed",
      "onShowInk",
      "onShowSync",
      "onThemeChanged",
      "openPptx",
      "pasteElements",
      "pasteSlide",
      "pickExportDir",
      "pickExportPdfPath",
      "pickPictureFile",
      "presenterEnd",
      "presenterInk",
      "presenterStart",
      "presenterSwap",
      "presenterSync",
      "printSlides",
      "privateFontData",
      "privateFontFaces",
      "redo",
      "removeSection",
      "renameSection",
      "reorderElement",
      "repasteSlide",
      "replacePictureBytes",
      "replacePictureUrl",
      "reportCloseSaveResult",
      "save",
      "saveAs",
      "saveStyleSidecar",
      "saveStyleTemplate",
      "setAdvanceTimes",
      "setAnimations",
      "setAutoSavePref",
      "setEffects",
      "setElementFont",
      "setElementParagraphFormat",
      "setLink",
      "setNotes",
      "setShapeAdjust",
      "setShowFullScreen",
      "setSlideHidden",
      "setSlideLayout",
      "setSlideSize",
      "setTableCellAnchor",
      "setTableColWidth",
      "setTableRowHeight",
      "setTextAnchor",
      "setTextBodyProps",
      "setTransition",
      "tableMerge",
      "tableStructure",
      "undo",
      "ungroupElement",
      "webSearch"
    ],
    "projectApi": [],
    "filesPaneApi": []
  }
};

/** Flat list of window.<global> names used by one app. */
export function globalsForApp(app) {
  const entry = HOST_SURFACE[app];
  if (!entry) throw new Error("unknown app " + app);
  return Object.keys(entry);
}

/** Every method for one app as "global.method". */
export function methodList(app) {
  const entry = HOST_SURFACE[app];
  if (!entry) throw new Error("unknown app " + app);
  const out = [];
  for (const globalName of Object.keys(entry)) {
    for (const method of entry[globalName]) out.push(globalName + "." + method);
  }
  return out;
}
