// Generated by scripts/brand/build-svg.py. Do not edit.
// Run `pnpm brand:build` after changing scripts/brand/geometry.py.

export type MarkArt = {
  readonly viewBox: string;
  readonly width: number;
  readonly height: number;
  readonly heads: readonly { readonly cx: number; readonly cy: number; readonly r: number }[];
  readonly bodies: readonly {
    readonly x: number;
    readonly y: number;
    readonly width: number;
    readonly height: number;
    readonly rx: number;
  }[];
  readonly ribbon: string;
  /** Whether the ribbon-over-figure crescent is drawn. Off below 24px:
   *  at that size it is one dark pixel row, not depth. */
  readonly depth: boolean;
};

/** Deep blue, signal azure, flow aqua: the gradient the mark is drawn in,
 *  paired with its on-dark ramp. Deliberately NOT a CSS token - the mark is
 *  the only place a gradient is allowed, and a token would invite it onto
 *  card backgrounds. The dark ramp exists because the light one's deep end
 *  measures 2.19:1 on the dark sidebar, which erases the left-hand figure.
 *
 *  Each `className` is spelled out rather than composed: Tailwind extracts
 *  class candidates by scanning source text, so a template literal built
 *  from these hexes would generate no CSS at all. */
export const BRAND_GRADIENT = [
  { offset: "0", className: "[stop-color:#0044E3] dark:[stop-color:#4D8DFF]" },
  { offset: ".52", className: "[stop-color:#00B4FC] dark:[stop-color:#35CBFF]" },
  { offset: "1", className: "[stop-color:#02DEF5] dark:[stop-color:#5AF0FF]" },
] as const;

/** Where the ribbon crosses a figure. */
export const MARK_SHADE_CLASS = "[fill:#0A34C4] dark:[fill:#1B4AD8]";

export const MARK: MarkArt = {
    viewBox: "0 0 128 92",
    width: 128,
    height: 92,
    heads: [
      { cx: 15, cy: 14, r: 14 },
      { cx: 113, cy: 14, r: 14 },
    ],
    bodies: [
      { x: 0, y: 31.5, width: 30, height: 47.5, rx: 15 },
      { x: 98, y: 31.5, width: 30, height: 47.5, rx: 15 },
    ],
    ribbon:
      "M0 53.675C5.748 57.151 10.517 61.753 15.81 65.817C17.818 67.351 21.31 69.981 23.989 70C26.776 70 30.538 67.104 32.606 65.495C34.078 64.351 35.51 63.155 36.942 61.963C44.942 55.303 53.021 48.85 64 48.8C74.979 48.85 83.058 55.303 91.058 61.963C92.49 63.155 93.922 64.351 95.394 65.495C97.462 67.104 101.224 70 104.011 70C106.69 69.981 110.182 67.351 112.19 65.817C117.483 61.753 122.252 57.151 128 53.675L128 81.36C124.737 84.004 121.382 86.493 117.651 88.444C113.356 90.66 108.927 91.965 104.069 92C93.08 91.978 84.989 85.536 76.982 78.87C75.508 77.643 74.035 76.412 72.519 75.237C70.459 73.639 66.769 70.813 64 70.8C61.231 70.813 57.541 73.639 55.481 75.237C53.965 76.412 52.492 77.643 51.018 78.87C43.011 85.536 34.92 91.978 23.931 92C19.073 91.965 14.644 90.66 10.349 88.444C6.618 86.493 3.263 84.004 0 81.36Z",
    depth: true,
  };

/** 16-24px: wider head gap, thicker band, shallower wave, no depth shade. */
export const MARK_COMPACT: MarkArt = {
    viewBox: "0 0 128 92",
    width: 128,
    height: 92,
    heads: [
      { cx: 15, cy: 14, r: 14 },
      { cx: 113, cy: 14, r: 14 },
    ],
    bodies: [
      { x: 0, y: 32.6, width: 30, height: 45.4, rx: 15 },
      { x: 98, y: 32.6, width: 30, height: 45.4, rx: 15 },
    ],
    ribbon:
      "M0 53.552C5.704 56.61 10.55 60.734 15.864 64.353C17.998 65.8 21.289 67.983 23.988 68C26.662 68 29.956 65.83 32.069 64.399C33.694 63.298 35.273 62.127 36.853 60.961C45.141 54.842 53.231 49.244 64 49.2C74.769 49.244 82.859 54.842 91.147 60.961C92.727 62.127 94.306 63.298 95.931 64.399C98.044 65.83 101.338 68 104.012 68C106.711 67.983 110.002 65.8 112.136 64.353C117.45 60.734 122.296 56.61 128 53.552L128 82.541C124.694 84.916 121.302 87.128 117.601 88.844C113.271 90.825 108.847 91.969 104.068 92C93.289 91.981 85.188 86.393 76.893 80.269C75.311 79.101 73.73 77.928 72.103 76.824C69.978 75.382 66.689 73.211 64 73.2C61.311 73.211 58.022 75.382 55.897 76.824C54.27 77.928 52.689 79.101 51.107 80.269C42.812 86.393 34.711 91.981 23.932 92C19.153 91.969 14.729 90.825 10.399 88.844C6.698 87.128 3.306 84.916 0 82.541Z",
    depth: false,
  };

/** Below this the full mark loses its head gap; Logo swaps in MARK_COMPACT. */
export const COMPACT_MAX_SIZE = 24;
