// GENERATED from server/internal/service/reserved_slugs.json — pnpm generate:reserved-slugs
export const RESERVED_SLUGS = [
  "_next",
  "admin",
  "api",
  "assets",
  "auth",
  "enterprise",
  "features",
  "forgot-password",
  "healthz",
  "inbox",
  "invitations",
  "invite",
  "learn",
  "login",
  "me",
  "meetings",
  "members",
  "my-tasks",
  "new",
  "onboarding",
  "orgs",
  "pricing",
  "public",
  "register",
  "reset-password",
  "settings",
  "solutions",
  "static",
  "tasks",
  "verify",
  "why-uniwork",
  "workspaces",
  "ws"
] as const;
