export { createPptxCommandMap, findPptxCommand, type PptxCommand, type PptxCommandCapability, type PptxCommandId } from "./command-map";
export { PptxSlideRail, type PptxSlideRailProps, type PptxSlideView } from "./slide-rail";
export { PptxPresenter, type PptxPresenterProps } from "./presenter";
export { PptxStatusBar, pptxLanguageLabel, type PptxStatusBarProps, type PptxStatusCounts } from "./status-bar";
export { PptxToolbar, type PptxToolbarProps } from "./toolbar";
export { PptxTabStrip, pptxTabDomId, pptxTabPanelId, type PptxTabStripProps } from "./toolbar/pptx-tab-strip";
export { PptxCommandGroups, PPTX_NARROW_COMMAND_QUERY, type PptxCommandGroupsProps } from "./toolbar/command-groups";
export { PptxCommandButton, type PptxCommandButtonProps } from "./toolbar/command-button";
export { PptxQuickAccess, PptxTabRowTrailing, type PptxQuickAccessProps, type PptxTabRowTrailingProps } from "./toolbar/tab-row-controls";
export { PptxFindBar, type PptxFindBarProps } from "./toolbar/find-bar";
export { PPTX_FIND_COMMAND, PPTX_QUICK_ACCESS_COMMANDS, PPTX_TAB_ROW_COMMANDS, PPTX_TOOLBAR_TABS, PPTX_VIEW_TOGGLE_COMMAND, computeToolbarOverflow, firstRovingIndex, nextRovingEnabledIndex, nextTabIndex, orderGroupsForNarrow, tabIsEmpty, toolbarCommandIds, type PptxGroupId, type PptxTabId, type PptxToolbarGroup, type PptxToolbarOverflow, type PptxToolbarTab } from "./toolbar/tabs";
export { PptxSelectionOverlay, type PptxSelectionOverlayProps } from "./selection/pptx-selection-overlay";
export { usePptxSelection, type PptxSelectionController, type PptxSelectionPreviewBox, type UsePptxSelectionOptions } from "./selection/use-pptx-selection";
export { applyGesture, beginGesture, gestureCommitRequests, gestureHandleAt, gestureIsNoop, type PptxGesture, type PptxGestureContext, type PptxGestureKind, type PptxGestureMember, type PptxPreviewBox } from "./selection/gesture";
export { PPTX_MIN_BOX_PX, PPTX_RESIZE_HANDLES, handlePosition, hitElement, hitHandle, marqueeSelection, moveBox, normalizeRect, rectsIntersect, resizeBox, rotateDegrees, rotateHandlePosition, selectionBounds, transformWithinBounds, unionBox, type PptxBox, type PptxHandleId, type PptxMarquee, type PptxPoint } from "./selection/geometry";
export { EMPTY_SELECTION, pruneSelection, selectAt, selectionHas, setSelection, type PptxSelectionState } from "./selection/selection-model";
export { PptxEditor, type PptxEditorProps } from "./pptx-editor";
export { PptxEditorView, type PptxEditorViewProps } from "./editor-view";
export { buildSlideSvg, collectRenderNodeBoxes, type SlideSvgDocument, type SlideSvgOptions } from "./canvas/build-slide-svg";
export { SvgNodeView, PptxCanvasSurface, type PptxCanvasContent, type PptxCanvasSurfaceProps } from "./canvas/pptx-canvas-surface";
export { PptxCanvasZoom, type PptxCanvasZoomProps } from "./canvas/pptx-canvas-zoom";
export { createPptxDeckRenderer, type PptxDeckModel, type PptxDeckRenderer, type PptxRenderInput } from "./canvas/deck-renderer";
export { assertPptxRendererModule, loadPptxRendererModule, type PptxRendererModule } from "./canvas/renderer-module";
export { readPptxPalette, type PptxCanvasPalette, type PptxImageSize } from "./canvas/paint";
export type { PptxNodeBox, PptxRenderSlide, PptxSlideSize, PptxViewport } from "./canvas/render-tree";
export { useElementWidth, usePptxDeckRenderer, usePptxPalette, usePptxRendererModule, useSlideRendition, type PptxDeckRendererInput, type PptxRendererState } from "./canvas/use-canvas-host";
export { clearPptxThumbnailCache, PPTX_THUMBNAIL_WIDTH, pptxThumbnailKey, usePptxThumbnails, type PptxThumbnailSlide } from "./canvas/use-pptx-thumbnails";
export { serializeSvgNode, slideSvgMarkup, svgDataUrl, type SvgNode } from "./canvas/svg-node";
export { PPTX_FALLBACK_FIT_WIDTH, PPTX_ZOOM_MAX, PPTX_ZOOM_MIN, PPTX_ZOOM_STEPS, clampZoom, resolveFitWidth, slideDisplaySize, stepZoom, zoomPercent } from "./canvas/zoom";