#!/usr/bin/env bash
# Make sure the local LiveKit container is running when this checkout uses
# localhost LiveKit (empty LIVEKIT_URL, or ws://localhost:7880 / 127.0.0.1).
# Cloud LiveKit is left alone. Set SKIP_LIVEKIT=1 to opt out.
#
# Writes livekit.dev.yaml.local (gitignored via *.local) with the webhook URL
# pointed at this checkout's PORT, then starts docker-compose.livekit.yml.
set -euo pipefail

ENV_FILE="${1:-.env}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

COMPOSE_FILE="docker-compose.livekit.yml"
TEMPLATE="livekit.dev.yaml"
LOCAL_CONFIG="livekit.dev.yaml.local"
# Must match keys in livekit.dev.yaml / docker-compose comments.
DEFAULT_URL="ws://localhost:7880"
DEFAULT_KEY="devkey"
DEFAULT_SECRET="secret_must_be_at_least_32_chars"

LIVEKIT_ENV_SNIPPET=".livekit.env.local"

if [ "${SKIP_LIVEKIT:-}" = "1" ]; then
  rm -f "$LIVEKIT_ENV_SNIPPET"
  echo "==> SKIP_LIVEKIT=1 — not starting local LiveKit."
  exit 0
fi

if [ ! -f "$ENV_FILE" ]; then
  echo "Missing env file: $ENV_FILE"
  echo "Create .env from .env.example, or run 'make worktree-env' and use .env.worktree."
  exit 1
fi

if [ ! -f "$TEMPLATE" ]; then
  echo "Missing $TEMPLATE — cannot start local LiveKit."
  exit 1
fi

set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a
# shellcheck disable=SC1091
. "$(dirname "$0")/local-env.sh"

PORT="${PORT:-8080}"
LIVEKIT_URL="${LIVEKIT_URL:-}"

livekit_host=""
parse_livekit_url() {
  local rest authority hostport
  [ -z "$LIVEKIT_URL" ] && return 0
  rest="${LIVEKIT_URL#*://}"
  rest="${rest%%\?*}"
  authority="${rest%%/*}"
  hostport="${authority##*@}"
  if [[ "$hostport" == \[* ]]; then
    livekit_host="${hostport#\[}"; livekit_host="${livekit_host%%]*}"
  else
    livekit_host="${hostport%%:*}"
  fi
}
parse_livekit_url

is_local_livekit() {
  if [ -z "$LIVEKIT_URL" ]; then
    return 0
  fi
  case "$livekit_host" in
    localhost|127.0.0.1|::1) return 0 ;;
    *) return 1 ;;
  esac
}

if ! is_local_livekit; then
  rm -f "$LIVEKIT_ENV_SNIPPET"
  echo "==> LIVEKIT_URL points at ${livekit_host:-remote} — skipping local LiveKit container."
  exit 0
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "✗ docker is required for local LiveKit (or set SKIP_LIVEKIT=1 / use cloud LIVEKIT_URL)."
  exit 1
fi

# Fill session defaults so `make start` works even when .env left the knobs blank.
if [ -z "${LIVEKIT_URL}" ]; then
  export LIVEKIT_URL="$DEFAULT_URL"
fi
if [ -z "${LIVEKIT_API_KEY}" ]; then
  export LIVEKIT_API_KEY="$DEFAULT_KEY"
fi
if [ -z "${LIVEKIT_API_SECRET}" ]; then
  export LIVEKIT_API_SECRET="$DEFAULT_SECRET"
fi

# Persist defaults into a sourced snippet for run-app.sh (same shell cannot inherit
# exports from a child). Written every ensure so PORT/webhook stay in sync.
cat > "$LIVEKIT_ENV_SNIPPET" <<EOF
# Generated by scripts/ensure-livekit.sh — do not commit (*.local).
export LIVEKIT_URL="${LIVEKIT_URL}"
export LIVEKIT_API_KEY="${LIVEKIT_API_KEY}"
export LIVEKIT_API_SECRET="${LIVEKIT_API_SECRET}"
export MEETING_PROVIDER="${MEETING_PROVIDER:-livekit}"
EOF

webhook_url="http://host.docker.internal:${PORT}/api/v1/integrations/livekit/webhook"
tmp_config="$(mktemp)"
# Replace any host.docker.internal:<port> webhook target with this checkout's PORT.
sed -E "s|(host\\.docker\\.internal:)[0-9]+/api/v1/integrations/livekit/webhook|\\1${PORT}/api/v1/integrations/livekit/webhook|" \
  "$TEMPLATE" > "$tmp_config"

need_recreate=0
if [ ! -f "$LOCAL_CONFIG" ] || ! cmp -s "$tmp_config" "$LOCAL_CONFIG"; then
  mv "$tmp_config" "$LOCAL_CONFIG"
  need_recreate=1
else
  rm -f "$tmp_config"
fi

echo "==> Ensuring local LiveKit is running on ${LIVEKIT_URL} (webhook → ${webhook_url})..."
if [ "$need_recreate" = "1" ]; then
  docker compose -f "$COMPOSE_FILE" up -d --force-recreate livekit
else
  docker compose -f "$COMPOSE_FILE" up -d livekit
fi

echo "==> Waiting for LiveKit to accept connections on :7880..."
ready=0
for _ in $(seq 1 60); do
  if curl -sf -o /dev/null "http://127.0.0.1:7880/" 2>/dev/null \
    || curl -sf -o /dev/null "http://localhost:7880/" 2>/dev/null; then
    ready=1
    break
  fi
  # LiveKit may answer with a non-2xx on / while still listening — accept any TCP.
  if command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 7880 2>/dev/null; then
    ready=1
    break
  fi
  sleep 1
done

if [ "$ready" != "1" ]; then
  echo "✗ LiveKit did not become ready on port 7880."
  docker compose -f "$COMPOSE_FILE" logs --tail=40 livekit || true
  exit 1
fi

echo "✓ LiveKit ready (local Docker). API key: ${LIVEKIT_API_KEY}"
echo "  Logs follow with make start / make dev (docker compose logs -f livekit)."
