#!/usr/bin/env bash
# Generate .env.worktree for a git worktree: its own database on the shared
# PostgreSQL container and its own backend/frontend ports, derived from the
# worktree path so several worktrees (and several agents) can run at once
# without stepping on each other's data or ports.
set -euo pipefail

ENV_FILE="${1:-.env.worktree}"

if [ -f "$ENV_FILE" ] && [ "${FORCE:-0}" != "1" ]; then
  echo "Refusing to overwrite existing $ENV_FILE. Re-run with FORCE=1 to regenerate it."
  exit 1
fi

worktree_name="${WORKTREE_NAME:-$(basename "$PWD")}"
slug="$(printf '%s' "$worktree_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/_/g; s/__*/_/g; s/^_//; s/_$//')"
[ -z "$slug" ] && slug="uniwork"

hash_value="$(printf '%s' "$PWD" | cksum | awk '{print $1}')"
offset=$((hash_value % 1000))

postgres_db="uniwork_${slug}_${offset}"
postgres_port=5432
backend_port=$((18080 + offset))
frontend_port=$((13000 + offset))
frontend_origin="http://localhost:${frontend_port}"
metrics_port=$((19090 + offset))

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init-worktree-env.sh for worktree '${worktree_name}'.
# Shares the postgres/redis containers from docker-compose.yml with every
# other checkout; only the database name and the app ports are unique.
POSTGRES_DB=${postgres_db}
POSTGRES_USER=uniwork
POSTGRES_PASSWORD=uniwork
POSTGRES_PORT=${postgres_port}
DATABASE_URL=postgres://uniwork:uniwork@localhost:${postgres_port}/${postgres_db}?sslmode=disable
TEST_DATABASE_URL=postgres://uniwork:uniwork@localhost:${postgres_port}/${postgres_db}_test?sslmode=disable
REDIS_URL=redis://localhost:6379
REDIS_TEST_URL=redis://localhost:6379/15

PORT=${backend_port}
JWT_SECRET=dev-secret-change-me
FRONTEND_PORT=${frontend_port}
FRONTEND_ORIGIN=${frontend_origin}
METRICS_ADDR=127.0.0.1:${metrics_port}
LOCAL_UPLOAD_DIR=./server/data/uploads-${slug}
LOCAL_UPLOAD_BASE_URL=http://localhost:${backend_port}

NEXT_PUBLIC_API_URL=http://localhost:${backend_port}
NEXT_PUBLIC_WS_URL=ws://localhost:${backend_port}
NEXT_PUBLIC_APP_URL=${frontend_origin}
E2E_BASE_URL=${frontend_origin}

LIVEKIT_URL=
LIVEKIT_API_KEY=
LIVEKIT_API_SECRET=
EOF

echo "Generated $ENV_FILE for worktree '$worktree_name'"
echo "  Shared Postgres: localhost:${postgres_port}"
echo "  Database:        ${postgres_db} (tests: ${postgres_db}_test)"
echo "  Backend:         http://localhost:${backend_port}"
echo "  Frontend:        ${frontend_origin}"
echo ""
echo "Next steps:"
echo "  make setup-worktree"
echo "  make start-worktree"
