package router

import "net/http"

// Routes is the HTTP surface the mux binds. handler.New fills every field
// from *handlers so route files stay in this package.
type Routes struct {
	Health http.HandlerFunc
	Ready  http.HandlerFunc
	WS     http.HandlerFunc

	Config                     http.HandlerFunc
	RUM                        http.HandlerFunc
	AdminMe                    http.HandlerFunc
	AdminListOrganizations     http.HandlerFunc
	AdminGetOrganization       http.HandlerFunc
	AdminSuspendOrganization   http.HandlerFunc
	AdminUnsuspendOrganization http.HandlerFunc
	AdminChangePlan            http.HandlerFunc
	AdminTrace                 http.HandlerFunc
	AdminSystem                http.HandlerFunc
	AdminListFlags             http.HandlerFunc
	AdminListFlagOverrides     http.HandlerFunc
	AdminListAllFlagOverrides  http.HandlerFunc
	AdminSetFlagOverride       http.HandlerFunc
	AdminDeleteFlagOverride    http.HandlerFunc

	Register       http.HandlerFunc
	Login          http.HandlerFunc
	ForgotPassword http.HandlerFunc
	ResetPassword  http.HandlerFunc
	Refresh        http.HandlerFunc
	Logout         http.HandlerFunc
	MFAVerify      http.HandlerFunc
	AuthProviders  http.HandlerFunc
	GoogleStart    http.HandlerFunc
	GoogleCallback http.HandlerFunc

	Me                  http.HandlerFunc
	PatchMe             http.HandlerFunc
	UploadAvatar        http.HandlerFunc
	VerifyEmail         http.HandlerFunc
	ResendVerification  http.HandlerFunc
	MFASetup            http.HandlerFunc
	MFAConfirm          http.HandlerFunc
	MFADisable          http.HandlerFunc
	ListSessions        http.HandlerFunc
	RevokeSession       http.HandlerFunc
	RevokeOtherSessions http.HandlerFunc
	DeleteAccount       http.HandlerFunc
	PatchOnboarding     http.HandlerFunc
	CompleteOnboarding  http.HandlerFunc
	MyInvitations       http.HandlerFunc

	ListOrganizations  http.HandlerFunc
	CreateOrganization http.HandlerFunc
	GetOrganization    http.HandlerFunc
	ListOrgWorkspaces  http.HandlerFunc
	CreateOrgWorkspace http.HandlerFunc

	ListOrgMembers      http.HandlerFunc
	GetOrgMembershipMe  http.HandlerFunc
	PatchOrgMember      http.HandlerFunc
	DeactivateOrgMember http.HandlerFunc
	ReactivateOrgMember http.HandlerFunc
	LeaveOrganization   http.HandlerFunc

	InviteToOrganization http.HandlerFunc
	ListOrgInvitations   http.HandlerFunc
	RevokeOrgInvitation  http.HandlerFunc
	TransferOrgOwnership http.HandlerFunc

	ListPeople         http.HandlerFunc
	GetPerson          http.HandlerFunc
	PatchPersonProfile http.HandlerFunc
	ExportPeople       http.HandlerFunc

	ListDepartments    http.HandlerFunc
	CreateDepartment   http.HandlerFunc
	PatchDepartment    http.HandlerFunc
	ArchiveDepartment  http.HandlerFunc
	ReorderDepartments http.HandlerFunc

	GetWorkspaceBySlugs http.HandlerFunc
	ListWorkspaces      http.HandlerFunc
	PatchWorkspace      http.HandlerFunc
	GetWorkspaceMe      http.HandlerFunc
	ListMembers         http.HandlerFunc
	PatchMember         http.HandlerFunc
	DeleteMember        http.HandlerFunc
	CreateInvitation    http.HandlerFunc
	AcceptInvitation    http.HandlerFunc

	SeedWelcomeTask http.HandlerFunc

	ListTasks             http.HandlerFunc
	CreateTask            http.HandlerFunc
	GetTask               http.HandlerFunc
	UpdateTask            http.HandlerFunc
	PutTaskSuite          http.HandlerFunc
	DeleteTask            http.HandlerFunc
	ListComments          http.HandlerFunc
	CreateComment         http.HandlerFunc
	QueryTasks            http.HandlerFunc
	GroupedTasks          http.HandlerFunc
	BatchUpdateTasks      http.HandlerFunc
	BatchDeleteTasks      http.HandlerFunc
	ListMyTasks           http.HandlerFunc
	ListTaskChildren      http.HandlerFunc
	ListChildrenByParents http.HandlerFunc
	ChildTaskProgress     http.HandlerFunc
	SetTaskParent         http.HandlerFunc
	SetTaskDependency     http.HandlerFunc
	RemoveTaskDependency  http.HandlerFunc
	TableGroups           http.HandlerFunc
	TableRows             http.HandlerFunc
	TableFacets           http.HandlerFunc

	ListTaskStatuses        http.HandlerFunc
	CreateTaskStatus        http.HandlerFunc
	PatchTaskStatus         http.HandlerFunc
	DeleteTaskStatus        http.HandlerFunc
	ReorderTaskStatuses     http.HandlerFunc
	ListTaskLabels          http.HandlerFunc
	GetTaskLabel            http.HandlerFunc
	CreateTaskLabel         http.HandlerFunc
	PutTaskLabel            http.HandlerFunc
	DeleteTaskLabel         http.HandlerFunc
	ListTaskLabelsOnTask    http.HandlerFunc
	AttachTaskLabel         http.HandlerFunc
	DetachTaskLabel         http.HandlerFunc
	ListTaskProperties      http.HandlerFunc
	CreateTaskProperty      http.HandlerFunc
	PatchTaskProperty       http.HandlerFunc
	PutTaskPropertyValue    http.HandlerFunc
	DeleteTaskPropertyValue http.HandlerFunc

	ListTaskViews         http.HandlerFunc
	CreateTaskView        http.HandlerFunc
	GetTaskView           http.HandlerFunc
	PatchTaskView         http.HandlerFunc
	DeleteTaskView        http.HandlerFunc
	GetTaskViewPreference http.HandlerFunc
	PutTaskViewPreference http.HandlerFunc
	ListPins              http.HandlerFunc
	CreatePin             http.HandlerFunc
	DeletePin             http.HandlerFunc
	ReorderPins           http.HandlerFunc

	ListProjects          http.HandlerFunc
	SearchProjects        http.HandlerFunc
	CreateProject         http.HandlerFunc
	GetProject            http.HandlerFunc
	PutProject            http.HandlerFunc
	DeleteProject         http.HandlerFunc
	ListProjectResources  http.HandlerFunc
	CreateProjectResource http.HandlerFunc
	PutProjectResource    http.HandlerFunc
	DeleteProjectResource http.HandlerFunc

	UpdateComment          http.HandlerFunc
	DeleteComment          http.HandlerFunc
	ResolveComment         http.HandlerFunc
	UnresolveComment       http.HandlerFunc
	AddCommentReaction     http.HandlerFunc
	RemoveCommentReaction  http.HandlerFunc
	AddTaskReaction        http.HandlerFunc
	RemoveTaskReaction     http.HandlerFunc
	ListTaskSubscribers    http.HandlerFunc
	SubscribeTask          http.HandlerFunc
	UnsubscribeTask        http.HandlerFunc
	UnsubscribeTaskSubtree http.HandlerFunc
	ListTaskAttachments    http.HandlerFunc
	GetAttachment          http.HandlerFunc
	DeleteAttachment       http.HandlerFunc
	GetTaskTimeline        http.HandlerFunc
	CommentSubTaskPreview  http.HandlerFunc
	CreateCommentSubTasks  http.HandlerFunc
	PreviewCommentTriggers http.HandlerFunc

	// WorkManagementCapabilityStub backs every catalogue disposition:stubbed route.
	WorkManagementCapabilityStub http.HandlerFunc

	ListNotifications          http.HandlerFunc
	UnreadNotificationCount    http.HandlerFunc
	MarkNotificationsRead      http.HandlerFunc
	MarkNotificationsUnread    http.HandlerFunc
	ArchiveNotifications       http.HandlerFunc
	GetNotificationPreferences http.HandlerFunc
	PutNotificationPreferences http.HandlerFunc
	PushConfig                 http.HandlerFunc
	SubscribePush              http.HandlerFunc
	UnsubscribePush            http.HandlerFunc

	AiCapabilities       http.HandlerFunc
	AskUni               http.HandlerFunc
	ListAiConversations  http.HandlerFunc
	ListAiMessages       http.HandlerFunc
	DeleteAiConversation http.HandlerFunc
	WorkspaceAiUsage     http.HandlerFunc
	OrganizationAiUsage  http.HandlerFunc

	ListPlans          http.HandlerFunc
	GetSubscription    http.HandlerFunc
	ChangePlan         http.HandlerFunc
	CancelSubscription http.HandlerFunc
	ResumeSubscription http.HandlerFunc
	CreateCheckout     http.HandlerFunc

	ListOrgAgents       http.HandlerFunc
	CreateOrgAgent      http.HandlerFunc
	PatchAgent          http.HandlerFunc
	ListWorkspaceAgents http.HandlerFunc
	AddWorkspaceAgent   http.HandlerFunc

	ListAuditEvents     http.HandlerFunc
	GetAuditEvent       http.HandlerFunc
	ListResourceHistory http.HandlerFunc
	GetAuditRetention   http.HandlerFunc
	SetAuditRetention   http.HandlerFunc
	ListAuditExports    http.HandlerFunc
	CreateAuditExport   http.HandlerFunc
	GetAuditExport      http.HandlerFunc

	ListMeetings         http.HandlerFunc
	CreateMeeting        http.HandlerFunc
	CreateInstantMeeting http.HandlerFunc
	GetMeeting           http.HandlerFunc
	UpdateMeeting        http.HandlerFunc
	DeleteMeeting        http.HandlerFunc
	StartMeeting         http.HandlerFunc
	EndMeeting           http.HandlerFunc
	CancelMeeting        http.HandlerFunc
	TransferHost         http.HandlerFunc
	ListNotes            http.HandlerFunc
	CreateNote           http.HandlerFunc
	MeetingToken         http.HandlerFunc
	JoinMeeting          http.HandlerFunc
	ListParticipants     http.HandlerFunc
	InviteParticipant    http.HandlerFunc
	ListInvitations      http.HandlerFunc
	RespondInvitation    http.HandlerFunc
	RemoveParticipant    http.HandlerFunc
	ListInviteLinks      http.HandlerFunc
	CreateInviteLink     http.HandlerFunc
	RevokeInviteLink     http.HandlerFunc
	ResolveInviteLink    http.HandlerFunc
	ListJoinRequests     http.HandlerFunc
	CreateJoinRequest    http.HandlerFunc
	ApproveJoinRequest   http.HandlerFunc
	RejectJoinRequest    http.HandlerFunc
	CancelJoinRequest    http.HandlerFunc
	MeetingStatistics    http.HandlerFunc
	MeetingActivity      http.HandlerFunc
	AppendTranscript     http.HandlerFunc
	ListTranscript       http.HandlerFunc
	AppendChatMessage    http.HandlerFunc
	ListChatMessages     http.HandlerFunc
	GetMeetingSummary    http.HandlerFunc
	CreateSummary        http.HandlerFunc
	CreateSummaryTasks   http.HandlerFunc
	StartRecording       http.HandlerFunc
	StopRecording        http.HandlerFunc
	ListRecordings       http.HandlerFunc
	MeetingCalendar      http.HandlerFunc
	MeetingCapabilities  http.HandlerFunc
	LiveKitWebhook       http.HandlerFunc
	MeetingLobbyWS       http.HandlerFunc

	LookupChatUser              http.HandlerFunc
	GetChatBlockStatus          http.HandlerFunc
	BlockChatUser               http.HandlerFunc
	UnblockChatUser             http.HandlerFunc
	ListChatNicknames           http.HandlerFunc
	SetChatNickname             http.HandlerFunc
	SearchChatGifs              http.HandlerFunc
	TrendingChatGifs            http.HandlerFunc
	SearchChatStickers          http.HandlerFunc
	TrendingChatStickers        http.HandlerFunc
	GetChatMediaStatus          http.HandlerFunc
	MintChatVoiceToken          http.HandlerFunc
	ListPendingChatVoiceInvites http.HandlerFunc
	GetWorkspaceChatRoom        http.HandlerFunc
	EnsureWorkspaceChatRoom     http.HandlerFunc
	ListChatRooms               http.HandlerFunc
	ResolveDM                   http.HandlerFunc
	CreateChatGroup             http.HandlerFunc
	InviteChatGroupMembers      http.HandlerFunc
	ListChatRoomMembers         http.HandlerFunc
	PatchChatRoomMember         http.HandlerFunc
	PatchChatRoom               http.HandlerFunc
	RemoveChatRoomMember        http.HandlerFunc
	LeaveChatRoom               http.HandlerFunc
	ListWorkspaceChatMessages   http.HandlerFunc
	SendWorkspaceChatMessage    http.HandlerFunc
	ListChatRoomMessages        http.HandlerFunc
	GetChatRoomMessage          http.HandlerFunc
	SearchChatRoomMessages      http.HandlerFunc
	ListChatRoomMessagesAround  http.HandlerFunc
	SendChatRoomMessage         http.HandlerFunc
	SendChatVoiceMessage        http.HandlerFunc
	StreamChatVoiceMessage      http.HandlerFunc
	SendChatFileMessage         http.HandlerFunc
	StreamChatFileMessage       http.HandlerFunc
	VoteChatPollMessage         http.HandlerFunc
	ToggleChatMessageReaction   http.HandlerFunc
	EditChatMessage             http.HandlerFunc
	DeleteChatMessage           http.HandlerFunc
	ToggleChatMessagePin        http.HandlerFunc
	SignalChatVoiceInvite       http.HandlerFunc
	SignalChatVoiceAccept       http.HandlerFunc
	SignalChatVoiceHangup       http.HandlerFunc
	SignalChatTyping            http.HandlerFunc
}
