apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: uniwork-be
  namespace: reap-edge
spec:
  scheme: http
  passHost: pass
  timeout: { connect: 5s, read: 60s, send: 60s }
  externalNodes:
    - type: Domain
      name: uniwork-be.uniwork.svc.cluster.local
      port: 8080
      weight: 100
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: uniwork-fe
  namespace: reap-edge
spec:
  scheme: http
  passHost: pass
  timeout: { connect: 5s, read: 60s, send: 60s }
  externalNodes:
    - type: Domain
      name: uniwork-fe.uniwork.svc.cluster.local
      port: 3000
      weight: 100
