"""Render the landing artwork through the OpenAI Images API and commit the WebP.

Replaces the CDN fetch in build-images.py. The old sources were marketing
renders belonging to the previous Lovable prototype: they drew a product that
is not this one, carried English lettering baked into the pixels, and lived on
someone else's CDN. These are generated from prompts that live in the repo, so
the artwork has a source a reviewer can read and change.

Five of the six images carry interface lettering and are therefore rendered
once per locale, `<name>.<locale>.webp`. The hero carries no lettering and is
rendered once as `<name>.webp` — a second identical file would be a second
download for nothing.

Text inside a generated image cannot be translated, measured for contrast or
read by a screen reader, so every prompt holds the lettering to a few words and
names them exactly. Vietnamese diacritics are the part a model is most likely
to get wrong; `--check` re-renders a single image so a bad one can be redone
without paying for the set again.

Needs OPENAI_API_KEY in the environment or in .env at the repo root (.env is
git-ignored and .githooks/pre-commit refuses to commit one).

Run: pnpm landing:gen            # everything missing from the lock
     pnpm landing:gen hero       # just this one, re-rendered
"""

import base64
import hashlib
import io
import json
import os
import sys
import urllib.error
import urllib.request

from PIL import Image

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
OUT = os.path.join(ROOT, "apps", "web", "public", "landing")
HERE = os.path.dirname(os.path.abspath(__file__))
PROMPTS = os.path.join(HERE, "prompts.json")
LOCK = os.path.join(HERE, "artwork.lock.json")

ENDPOINT = "https://api.openai.com/v1/images/generations"
LOCALES = ("vi", "en")
WIDTH = 1600
QUALITY = 82


def api_key() -> str:
    key = os.environ.get("OPENAI_API_KEY", "").strip()
    if key:
        return key
    env = os.path.join(ROOT, ".env")
    if os.path.exists(env):
        for line in open(env, encoding="utf-8"):
            name, _, value = line.partition("=")
            if name.strip() == "OPENAI_API_KEY":
                return value.strip().strip('"').strip("'")
    sys.exit("OPENAI_API_KEY is not set. Put it in the environment or in .env at the repo root.")


def compose(spec: dict, style: str, locale: str | None) -> str:
    """One prompt string: the shared style, the scene, then the exact lettering."""
    parts = [style, spec["prompt"]]
    if locale:
        parts.append(spec["text"][locale])
    else:
        parts.append("No text, no lettering of any kind anywhere in the image.")
    return "\n\n".join(parts)


def generate(key: str, model: str, quality: str, size: str, prompt: str) -> bytes:
    body = json.dumps(
        {"model": model, "prompt": prompt, "size": size, "quality": quality, "n": 1, "output_format": "png"}
    ).encode()
    req = urllib.request.Request(
        ENDPOINT,
        data=body,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    try:
        # Image generation is slow; the default socket timeout would give up first.
        with urllib.request.urlopen(req, timeout=300) as resp:
            payload = json.load(resp)
    except urllib.error.HTTPError as e:
        sys.exit(f"OpenAI returned {e.code}: {e.read().decode()[:500]}")
    return base64.b64decode(payload["data"][0]["b64_json"])


def encode(png: bytes, width: int) -> bytes:
    img = Image.open(io.BytesIO(png))
    if img.width > width:
        height = round(img.height * width / img.width)
        img = img.resize((width, height), Image.LANCZOS)
    buf = io.BytesIO()
    # method=6 is the slowest and smallest setting; this runs by hand, not in CI.
    img.convert("RGB").save(buf, "WEBP", quality=QUALITY, method=6)
    return buf.getvalue()


def sha(b: bytes | str) -> str:
    return hashlib.sha256(b if isinstance(b, bytes) else b.encode()).hexdigest()


def main() -> int:
    spec = json.load(open(PROMPTS, encoding="utf-8"))
    only = set(sys.argv[1:])
    lock = json.load(open(LOCK, encoding="utf-8")) if os.path.exists(LOCK) else {"images": {}}
    lock["_"] = "Generated by scripts/landing/gen-images.py. Run `pnpm landing:gen`."
    lock["model"] = spec["model"]
    lock.setdefault("images", {})
    os.makedirs(OUT, exist_ok=True)
    key = api_key()

    for name, image in spec["images"].items():
        if only and name not in only:
            continue
        for locale in (LOCALES if image["localized"] else (None,)):
            stem = f"{name}.{locale}" if locale else name
            prompt = compose(image, spec["style"], locale)
            entry = lock["images"].get(stem)
            # A prompt that has not changed and an output already on disk is
            # not worth paying for twice; an explicit name on the command line
            # overrides that, which is how a bad render gets redone.
            if not only and entry and entry["prompt_sha256"] == sha(prompt) and os.path.exists(
                os.path.join(OUT, f"{stem}.webp")
            ):
                print(f"  skip {stem}.webp (unchanged)")
                continue
            print(f"  render {stem}.webp ({image['size']}) ...", flush=True)
            webp = encode(generate(key, spec["model"], spec["quality"], image["size"], prompt), WIDTH)
            open(os.path.join(OUT, f"{stem}.webp"), "wb").write(webp)
            lock["images"][stem] = {
                "size": image["size"],
                "locale": locale,
                "prompt_sha256": sha(prompt),
                "bytes": len(webp),
                "sha256": sha(webp),
            }
            print(f"  wrote {stem}.webp ({len(webp) // 1024} KB)")

    json.dump(lock, open(LOCK, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    open(LOCK, "a", encoding="utf-8").write("\n")
    total = sum(v["bytes"] for v in lock["images"].values()) / 1024 / 1024
    print(f"lock updated, {len(lock['images'])} images, {total:.2f} MB total")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
