import type { ChatContact } from "@uniwork/core/chat/contacts-store";
import type { GroupChat } from "@uniwork/core/chat/groups-store";
import type { ChatRoomRecord } from "@uniwork/core/api/endpoints/chat";
import type { ComposerMessagePriority } from "@uniwork/core/chat/composer-priority";
import type { Member } from "@uniwork/core/types/workspace";
import type { ChatSidebarTarget } from "./chat-sidebar";
import type { ChatRoomPreview } from "./chat-sidebar-preview";
import type { ChatNameContextEntry, GroupMemberProfile } from "./chat-page-utils";
import type { ChatMessage } from "./chat-messages";

export type ChatPageContentProps = {
  target: ChatSidebarTarget;
  setTarget: React.Dispatch<React.SetStateAction<ChatSidebarTarget>>;
  currentUserId: string;
  headerTitle: string;
  contacts: ChatContact[];
  groups: GroupChat[];
  channels: ChatRoomRecord[];
  workHubEnabled: boolean;
  activeContact: ChatContact | null;
  activeGroup: GroupChat | null;
  activeChannel: ChatRoomRecord | null;
  workspaceId: string;
  messageRefreshKey?: number;
  activeRoomId: string | null;
  showLoading: boolean;
  connectError: string | null;
  pendingOutboxCount?: number;
  isWorkspaceError: boolean;
  onRefetchWorkspace: () => void;
  workspaceRoomId: string | null;
  unreadByRoomId: Record<string, number>;
  mentionUnreadByRoomId: Record<string, number>;
  roomPreviewsByRoomId: Record<string, ChatRoomPreview>;
  unreadBadgesReady: boolean;
  nicknamesByUserId: Record<string, string>;
  nameContext: ChatNameContextEntry[];
  replyTo: ChatMessage | null;
  onReplyToChange: React.Dispatch<React.SetStateAction<ChatMessage | null>>;
  draft: string;
  onDraftChange: React.Dispatch<React.SetStateAction<string>>;
  composerPriority: ComposerMessagePriority | null;
  onComposerPriorityChange: React.Dispatch<React.SetStateAction<ComposerMessagePriority | null>>;
  onSend: () => void;
  onSendMedia: (body: string) => void | Promise<void>;
  onSendVoice: (recording: { blob: Blob; durationMs: number }) => Promise<void>;
  onSendFile: (file: File) => Promise<void>;
  groupSettingsOpen: boolean;
  onGroupSettingsOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  dmSettingsOpen: boolean;
  onDmSettingsOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  dmBlocked: boolean;
  dmBlockedByMe: boolean;
  dmBlockedMe: boolean;
  onBlockContact: () => void;
  onUnblockContact: () => void;
  blockingContact: boolean;
  unblockingContact: boolean;
  addMembersOpen: boolean;
  onAddMembersOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  createGroupOpen: boolean;
  onCreateGroupOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  channelSettingsOpen: boolean;
  onChannelSettingsOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  creatingGroup: boolean;
  onCreateGroup: (members: ChatContact[], name: string) => void;
  invitingMembers: boolean;
  onAddGroupMembers: (members: ChatContact[]) => void;
  leavingConversation: boolean;
  onLeaveGroup: () => void;
  onLeaveDm: () => void;
  onLeaveChannel: () => void;
  groupMemberProfiles: Record<string, GroupMemberProfile>;
  typingLabel: string | null;
  onVoiceCall: () => void;
  voiceCallDisabled: boolean;
  onVideoCall: () => void;
  videoCallDisabled: boolean;
  workspaceMembers: Member[];
  workspaceSettingsOpen: boolean;
  onWorkspaceSettingsOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  messageSearchOpen: boolean;
  onMessageSearchOpenChange: React.Dispatch<React.SetStateAction<boolean>>;
  jumpToMessageId: string | null;
  onJumpToMessageIdChange: React.Dispatch<React.SetStateAction<string | null>>;
  chatSendRestricted: boolean;
  chatSendMutedByModerator: boolean;
  canPinMessages: boolean;
  canCreatePolls: boolean;
  canCreateNotes: boolean;
  t: (key: string, options?: Record<string, string | number>) => string;
};
