// C3 (UNI-924) protection tests: the model carries set_protection /
// set_write_protection into SaveOptions (the vendored writer emits or removes
// w:documentProtection / w:writeProtection) while an untouched document keeps
// both options undefined so word/settings.xml stays byte-identical. The hash
// port is pinned against a vector generated by the vendored protection.ts.
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  DOCX_PROTECTION_ALGORITHM_SID,
  DocxSessionModel,
  createDocxAdapter,
  hashProtectionPassword,
  protectionHash,
  type DocProtection,
  type DocxParsed,
  type DocxSaveBlock,
  type DocxSaveOptions,
  type WriteProtection,
} from "../src/docx";
import { createFakeDocxEngine, makeFakeDocxBytes } from "./fake-docx-engine";

/** Typed-error oracle: callers branch on `code`, never on message text. */
const errCode = (fn: () => unknown): string => {
  try {
    fn();
  } catch (e) {
    return String((e as { code?: string }).code ?? e);
  }
  return "";
};

const errCodeOf = async (promise: Promise<unknown>): Promise<string> => {
  try {
    await promise;
  } catch (e) {
    return String((e as { code?: string }).code ?? e);
  }
  return "";
};

function fromBase64(base64: string): Uint8Array {
  return Uint8Array.from(atob(base64), (character) => character.charCodeAt(0));
}

function toBase64(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

// Generated by the VENDORED packages/docx-engine/src/protection.ts with a
// pinned salt (scratchpad fixture step): password "Passw0rd!", spin 1000,
// salt = bytes 1..16, SHA-512 sid 14. The port must reproduce this hash.
const VECTOR = {
  password: "Passw0rd!",
  spinCount: 1000,
  saltBase64: "AQIDBAUGBwgJCgsMDQ4PEA==",
  hashBase64: "zxVPdka//ioqPQioR9V2/oniX0TRg2cZhDzNsByFk8EIovZm5UKRTwX0/uvYl5DKc6PrvJsquel0p/tuZ00DMQ==",
};

const CREDENTIALS = {
  hash: VECTOR.hashBase64,
  salt: VECTOR.saltBase64,
  spinCount: VECTOR.spinCount,
  algorithmSid: DOCX_PROTECTION_ALGORITHM_SID,
};

const RESTRICTION: DocProtection = { edit: "readOnly", enforced: true };
const MODIFY: WriteProtection = { recommended: true };

const SOURCE = makeFakeDocxBytes({ blocks: [{ type: "paragraph", runs: [{ text: "body" }] }] });

interface ProtectionFixture {
  protection: DocProtection | null;
  writeProtection: WriteProtection | null;
}

/** Fake engine + a capture of every saveDocx call, with the fixture's
 * protection state fed into the parse the way the real parse.ts does. */
function createProtectionEngine(fixture: ProtectionFixture = { protection: null, writeProtection: null }) {
  const base = createFakeDocxEngine();
  const saves: Array<{ blocks: DocxSaveBlock[]; options: DocxSaveOptions | undefined }> = [];
  const engine = {
    async parseDocx(bytes: Uint8Array): Promise<DocxParsed> {
      const parsed = await base.parseDocx(bytes);
      parsed.protection = fixture.protection;
      parsed.writeProtection = fixture.writeProtection;
      return parsed;
    },
    async saveDocx(parsed: DocxParsed, blocks: DocxSaveBlock[], options?: DocxSaveOptions) {
      saves.push({ blocks, options });
      return base.saveDocx(parsed, blocks, options);
    },
    listPackageParts: base.listPackageParts,
  };
  return { engine, saves };
}

async function openModel(fixture?: ProtectionFixture) {
  const { engine, saves } = createProtectionEngine(fixture);
  const parsed = await engine.parseDocx(SOURCE);
  return { model: new DocxSessionModel(parsed), engine, saves };
}

async function openAdapter(fixture?: ProtectionFixture) {
  const { engine, saves } = createProtectionEngine(fixture);
  const adapter = createDocxAdapter({ engine });
  const out = await adapter.open({ bytes: SOURCE, format: "docx", document_id: "doc-protection" });
  if (out.outcome !== "opened") throw new Error("open failed: " + JSON.stringify(out));
  return { adapter, ref: out.document_model_ref, saves };
}

afterEach(() => {
  vi.unstubAllGlobals();
});

describe("docx protection password hash", () => {
  it("reproduces the vendored implementation's pinned vector", async () => {
    const hash = await protectionHash(VECTOR.password, fromBase64(VECTOR.saltBase64), VECTOR.spinCount);
    expect(toBase64(hash)).toBe(VECTOR.hashBase64);
  });

  it("generates a random salt, keeps the SHA-512 scheme and verifies by recomputation", async () => {
    const credentials = await hashProtectionPassword("s3cret", 1000);
    expect(credentials.spinCount).toBe(1000);
    expect(credentials.algorithmSid).toBe(DOCX_PROTECTION_ALGORITHM_SID);
    expect(fromBase64(credentials.salt)).toHaveLength(16);
    const recomputed = await protectionHash("s3cret", fromBase64(credentials.salt), 1000);
    expect(toBase64(recomputed)).toBe(credentials.hash);
    const wrong = await protectionHash("nope", fromBase64(credentials.salt), 1000);
    expect(toBase64(wrong)).not.toBe(credentials.hash);
  });

  it("fails closed when WebCrypto is unavailable", async () => {
    vi.stubGlobal("crypto", undefined);
    expect(await errCodeOf(hashProtectionPassword("s3cret", 1000))).toBe("crypto_unavailable");
    expect(await errCodeOf(protectionHash("s3cret", new Uint8Array([1]), 1000))).toBe("crypto_unavailable");
  });

  it("refuses an empty password, a bad spin count and an empty salt", async () => {
    expect(await errCodeOf(hashProtectionPassword("", 1000))).toBe("empty_password");
    expect(await errCodeOf(hashProtectionPassword("s3cret", 0))).toBe("bad_spin_count");
    expect(await errCodeOf(hashProtectionPassword("s3cret", 1.5))).toBe("bad_spin_count");
    expect(await errCodeOf(protectionHash("s3cret", new Uint8Array(0), 1000))).toBe("bad_salt");
  });
});

describe("docx protection model", () => {
  it("keeps an untouched document's options undefined", async () => {
    const { model } = await openModel({ protection: RESTRICTION, writeProtection: MODIFY });
    expect(model.isDirty).toBe(false);
    const { options } = model.savePlan();
    expect(options.protection).toBeUndefined();
    expect(options.writeProtection).toBeUndefined();
  });

  it("carries a restriction into SaveOptions.protection and copies the spec", async () => {
    const { model } = await openModel();
    const spec: DocProtection = { edit: "trackedChanges", enforced: true, ...CREDENTIALS };
    model.applyEdit({ op: "set_protection", protection: spec });
    expect(model.isDirty).toBe(true);
    expect(model.revision).toBe(1);
    spec.edit = "readOnly";
    const { options } = model.savePlan();
    expect(options.protection).toEqual({ edit: "trackedChanges", enforced: true, ...CREDENTIALS });
    const again = model.savePlan().options.protection!;
    again.edit = "forms";
    expect(model.savePlan().options.protection?.edit).toBe("trackedChanges");
  });

  it("carries a password-to-modify, including the recommended-only form", async () => {
    const { model } = await openModel();
    model.applyEdit({ op: "set_write_protection", writeProtection: { recommended: true } });
    expect(model.savePlan().options.writeProtection).toEqual({ recommended: true });
    model.applyEdit({ op: "set_write_protection", writeProtection: { recommended: true, ...CREDENTIALS } });
    expect(model.savePlan().options.writeProtection).toEqual({ recommended: true, ...CREDENTIALS });
  });

  it("null removes each tag; an empty writeProtection spec is refused", async () => {
    const { model } = await openModel({ protection: RESTRICTION, writeProtection: MODIFY });
    model.applyEdit({ op: "set_protection", protection: null });
    model.applyEdit({ op: "set_write_protection", writeProtection: null });
    expect(model.savePlan().options.protection).toBeNull();
    expect(model.savePlan().options.writeProtection).toBeNull();
    expect(errCode(() => model.applyEdit({ op: "set_write_protection", writeProtection: {} }))).toBe("empty_protection");
    // the refused spec never consumed a revision
    const before = model.revision;
    expect(errCode(() => model.applyEdit({ op: "set_write_protection", writeProtection: { recommended: false } }))).toBe("empty_protection");
    expect(model.revision).toBe(before);
  });

  it("refuses malformed restrictions and credentials", async () => {
    const { model } = await openModel();
    expect(errCode(() => model.applyEdit({ op: "set_protection", protection: { edit: "", enforced: true } }))).toBe("bad_protection");
    expect(errCode(() => model.applyEdit({ op: "set_protection", protection: { edit: "readOnly", enforced: "yes" as never } }))).toBe("bad_protection");
    expect(errCode(() => model.applyEdit({ op: "set_protection", protection: { edit: "readOnly", enforced: true, hash: "" } }))).toBe("bad_protection");
    expect(errCode(() => model.applyEdit({ op: "set_protection", protection: { edit: "readOnly", enforced: true, salt: 7 as never } }))).toBe("bad_protection");
    expect(errCode(() => model.applyEdit({ op: "set_protection", protection: { edit: "readOnly", enforced: true, spinCount: 0 } }))).toBe("bad_protection");
    expect(errCode(() => model.applyEdit({ op: "set_protection", protection: { edit: "readOnly", enforced: true, algorithmSid: 4 } }))).toBe("bad_protection");
    expect(errCode(() => model.applyEdit({ op: "set_write_protection", writeProtection: { hash: VECTOR.hashBase64, algorithmSid: 4 } }))).toBe("bad_protection");
    expect(model.isDirty).toBe(false);
  });

  it("routes both ops through applyEdit without touching the block plan", async () => {
    const { model } = await openModel({ protection: RESTRICTION, writeProtection: null });
    model.applyEdit({ op: "set_protection", protection: null });
    model.applyEdit({ op: "set_write_protection", writeProtection: { recommended: true, ...CREDENTIALS } });
    expect(model.revision).toBe(2);
    const { finalBlocks, options } = model.savePlan();
    expect(finalBlocks.every((block) => block.kind === "original")).toBe(true);
    expect(options.protection).toBeNull();
    expect(options.writeProtection).toEqual({ recommended: true, ...CREDENTIALS });
  });

  it("reaches saveDocx through the adapter edit channel and drains on rebase", async () => {
    const { adapter, ref, saves } = await openAdapter();
    adapter.edit(ref, { op: "set_protection", protection: { edit: "comments", enforced: true, ...CREDENTIALS } });
    adapter.edit(ref, { op: "set_write_protection", writeProtection: { recommended: true } });
    await adapter.serialize({ document_model_ref: ref, format: "docx" });
    expect(saves).toHaveLength(1);
    expect(saves[0]?.options?.protection).toEqual({ edit: "comments", enforced: true, ...CREDENTIALS });
    expect(saves[0]?.options?.writeProtection).toEqual({ recommended: true });
    // the rebased model has no pending options: the next untouched save omits both
    const untouched = await adapter.serialize({ document_model_ref: ref, format: "docx" });
    expect(saves).toHaveLength(2);
    expect(saves[1]?.options?.protection).toBeUndefined();
    expect(saves[1]?.options?.writeProtection).toBeUndefined();
    expect(untouched.bytes.length).toBeGreaterThan(0);
  });

  it("removal alone still reaches saveDocx when the parse carried a restriction", async () => {
    const { adapter, ref, saves } = await openAdapter({ protection: RESTRICTION, writeProtection: null });
    adapter.edit(ref, { op: "set_protection", protection: null });
    await adapter.serialize({ document_model_ref: ref, format: "docx" });
    expect(saves[0]?.options?.protection).toBeNull();
  });
});
